# 复杂系统

## 复杂系统的特征

- 组成部分或个体相对简单
- 各部分非线性相互作用
- 没有中心控制
- 涌现行为，例如层级结构、信息处理、动态、进化学习

## 动力学

- 系统随时间的变化
- 混沌系统，初始条件与运行规则已知，长期预测不可知，对初始值敏感但存在可预测的全局特性
- Logistic Map

## 分形

- 自我相似性，整体与局部相似
- 分形的维度，D维对象的边被反复切割为M个部分，每一切割水平有$M^D$个副本，假如副本个数为N，也就是说$N=M^D$，其维度$D = logN/logM$
- 数盒子测维度，计算有多少盒子与盒子的边长，改变盒子的边长，计算盒子的个数 $log[NumberOfBoxes] = D log[1/BoxSize]$

## 信息论

- 麦克斯韦妖
- 热动力学的墒测量做功时的热损失，热损失就是无序；统计学的墒测量能出现宏观状态的微观状态的数量，微观状态越少墒越低，越混合越无序。统计意义上热力学第二定律本质是宏观状态下微观状态数目趋向于最大
- 玻尔兹曼认为宏观状态的墒S是微观状态数W的自然对数的k倍，k是玻尔兹曼常数。更多的微观状态会提高宏观状态出现的可能，墒提高。
- 香农认为信息含量表示让人吃惊的程度
- 信息量$H = log_2 M$ M 表示以字节传递信息的可能性
- 信息整体$H = - \sum_{i=1}^{M}p_ilog_{2}p_i$ p 表示出现的概率
- Hffman编码可节省信息传递字节，进行压缩

## 进化

- 遗传算法，首先生成随机策略，对于随机策略计算适应性，然后对策略进行杂交与突变，重复这个过程直到足够好的策略产生
- 难预测，会产生过度适应，但会有新东西产生
- 编程上用if-else生成的树来进行突变

## 细胞自动机

- Conway的game of life
- Stanislaw Ulam 和 John von Neumann的细胞自动机，机器中的繁殖
- 元细胞自动机，一维仅考虑左右邻居，两个状态，共计256种模式，用二进制编码（Wolfram编码）
- 规则30被用作伪随机数生成器
- 四种分类：固定的，周期的，混沌的，局部的
- 作为动态系统考察，与 logistic map 同构
- 控制参数lambda，规则里黑色的比例，从固定到周期到混沌到周期到固定，存在混沌的边缘
- 第四种可以用来进行通用计算，但第四类很难定义，规则110可以作为通用计算机
- 细胞自动机可以用遗传算法来筛选规则演进
- 细胞自动机也可以用来理解信息交换，通过定义模式来进行




