# 量化投资

## 股票收益模型

- 股票指数可代表市场，收益率$r_M$
- 某股票跟市场的相关性是市场贝塔（market beta）$\beta_M$
- 市场之外的贡献阿尔法$\alpha$
- 特定股票收益率 $r = \alpha + \beta_M r_M$
- 资本资产定价模型（capital asset pricing model, CAPM）：所有股票阿尔法部分期望是零
- 套利定价理论（arbitrage pricing theory, APT）：除了市场因素，还有其他公用因素来解释股票收益 
- 宏观经济因子模型（macroeconomic factor model, MFM）：$r_i = u_i+\sum_{k=1}^{K}\beta_{ik}f_k$
- 成熟的商业模型可以确定一些共同因素，但也面临不确定性

## 风险

- 单只股票波动很大，一般会组合投资降低风险
- 单只股票波动率$\sigma_i$，两只股票之间的相关系数$\rho_{ij}$，股票组合波动率$\sigma_p^2 = \sum_{i=1}^nw_i^2\sigma_i^2 + \sum_{i\neq j}w_i\sigma_i\rho_{ij}\sigma_jw_j$，其中$w$是股票权重
- 两两间需要估计的参数多
- 因为组合的股票多而共同因素少，可以直接估计与共同因素的相关性来替代总体估计
- 但是除了共同部分还有股票特有特征，所以个股的波动是个体波动与整体波动的综合 $\sigma_i^2 = \sigma_{S,i}^2 + \sum_{l,m = 1,...,K}\beta_{il}\sigma_i\rho_{lm}\sigma_m\beta_{im}$，这里我们认为股票间波动可以用共同波动来解释$\sigma_i\rho_{ij}\sigma_j = \sum_{l,m = 1,...,K}\beta_{il}\sigma_i\rho_{lm}\sigma_m\beta_{im}$
- 所谓风险控制就是通过对每只股票权重的调节优化来降低波动率，但结果不稳定
- 通过风险控制就可以计算收益率，但毕竟有些因素是不可控的，解决的方法就是通过权重调整让其对总收益贡献为零或做空该因素对冲风险

## 收益

- 共同因素的收益可通过投资市场指数来获得
- 某特定共同因素的收益需要自己构建，smart beta
- 这属于被动投资，因为股票市场长期看总是上涨，所以收益不差
- 也存在主动投资，根据自己预测投资并不断调整，smart beta属于半被动投资
- 特异收益方面可以进行择时收益（timing skill），但一定注意风控

## 一般性投资

- 三要素：成本、收益、风险
- 时间序列分析：统计学
- 技术分析：根据价格曲线图形进行分析的一种方法，技术分析本质是经验分析，可以量化为模式进行识别，有些指标可以进行机理解释
- 收益的统计分析
        - 环比：以月为周期的相对收益率
        - 同比：以年为周期的相对收益率
        - 收益率一般是正态分布，但也可能是肥尾的，极端事件发生概率高；甚至是长尾，比较极端事件也有可能发生；还有可能出现黑天鹅，非常极端事件
        - 可预见事件会有过度反应然后回调，可进行事件驱动投资
- 影响价格因素的分析，要考虑专业知识、随机性、噪声、数据来源、混杂因素



