[数码相机教程笔记](http://www.cambridgeincolour.com/tutorials.htm)
=================

# 数码相机工作原理

## 传感器

- 8位图像每个像素可存储0-255的数值代表明暗，0为black，255为white
- the Bayer array 红色：蓝色：绿色= 1：1：2 人眼对绿色更敏感 马赛克阵列
- 去马赛克算法 田字格 损失分辨率 因此采用叠加复算 同一个色块被4个田字格重复使用 最边上的像素不要了
- 摩尔纹 线条干涉 与阵列排布模式有关
- 传感器阵列存在不感光区域与间隔区 用微棱镜引导间隔区的光

## 曝光三要素

- 光圈控景深
	- 大光圈 浅景深 同一点进光过多 焦外背景模糊
	- 小光圈 深景深 小孔衍射模糊
	- 考虑拍摄主题
- 快门控动态模糊
	- 1-30+ 夜晚与低光环境
	- 2-1/2 流水 大景深景观
	- 1/2-1/30 移动物体的动态模糊 手持需稳定
	- 1/50-1/100 典型环境
	- 1/250-1/500 运动与动作 望远摄影
	- 1/1000-1/4000 凝固瞬间
- ISO控噪点
	- 胶片50-200
	- 数码50-800
- 曝光三角形 各要素副作用记好 组合效果保证曝光准确
- 档位
	- auto 全自动
	- p iso固定
	- a 固定光圈ISO
	- s 固定快门速度ISO
	- m 全手动
	- b 固定光圈 手控快门
	- 肖像 最大光圈 最小景深
	- 景观 最小光圈 最大景深
	- 运动 1/250或更小的快门速度 最大光圈 高iso
	- 夜晚 慢速快门 高速iso 前景闪光
- 依赖相机测光

## 测光

- 反射光 白色总显示为18度灰
- 白增黑减 
	-全白场景还原为18度灰 直方图正态化 增曝可显示白色 
	-暗色环境还原后偏亮 减曝可显示黑色
- 曝光模式
	-点测光 平均测光
	-18度灰板测光
	-逆光肖像 特殊光源 用点测
- 曝光演绎 正确区分光源 防止高光溢出 了解相机曝光失误

## 景深

- 前景后景均模糊
- 模糊圈 用来确定景深 与传感器大小有关
- 焦外成像区 模糊效果 不一定是圈 可能是5-8边形
- 由光圈与对焦距离决定 大光圈小景深
- 跟焦距没关系 
	- 长焦望远放大 焦平面前后景深基本一致 视角小 焦外成像更模糊 使用主体突出特写 存在瞳孔放大效应
	- 广角贴近 焦平面前景深小 后景深大 适用于风景
- 对焦深度 大光圈小深度 小光圈大深度 深度指传感器可移动的范围

## 镜头

- 镜头导致的问题包括低对比度 色差 光晕 变形 模糊
- 焦距主要问题就是视角
- 透视效果严格讲与焦距无关 只与站的位置有关 但实际随焦距变化
	- <21mm 超广角 建筑摄影
	- 21-35mm 广角 风景
	- 35-70mm 正常 街道 纪实
	- 70-135mm 中度望远 肖像
	- 135-300+mm 望远 运动 鸟 野生动物
- 焦距与手持摄影 长焦曝光时间短防止摇晃 安全快门与焦距（35mm）等同
- 定焦与变焦 注意跟对焦的关系 一般最大光圈小一档或两档成像质量会好一些

## 白平衡

- 色温 不同温度下的光谱 高温偏低波长 低温偏高波长
	-1000-2000K 烛光
	-2500-3500K 白炽灯
	-3000-4000K 日出 日落
	-4000-5000K 荧光灯
	-5000-5500K 闪光灯
	-5000-6500K 晴天
	-6500-8000K 阴天
	-9000-10000K 阴影或阴霾天
- 绿-品红转换 调整人工光源 营造特殊氛围
- 使用RAW 通过参考物质还原场景
- 自动白平衡判断的是光源光 如果拍摄物体本身偏暖或冷 背景物会偏冷或暖 就需要手动调节 自动白平衡在有白色物体的画面中更准确
- 混合光下自动白平衡会分区对待 手动则为单一色调 可能失真

## 自动对焦

- 自动对焦传感器 检测对比度 可通过直方图理解 对比度最大对焦最锐
	- 对焦系统轻微改变对焦距离
	- 读取传感器对比度看变化如何
	- 根据上步结果调整对焦距离
	- 重复上面步骤
- 影响因素
	- 光亮度
	- 物体对比度
	- 物体动态
	- 选择对比度强 低动态 高亮度的物体对焦
- 对焦点
	- +表示二维对比度检测 更准 在中心
	- -表示一维对比度检测
- 自动对焦模式
	- 连续对焦&伺服对焦 移动物体对焦 耗电池
	- 一次对焦
	- 自动对焦辅助光 对比度小的静物比较适合
- 对焦位置
	- 人像对焦眼睛 对比度高
	- 偏离中心物体用中心对焦要偏后
	- 在条纹场景注意对焦方向

# 数码照片的品质

## 数码存储

- 图片用像素存储 像素用RGB存储 RGB用01存储 8位00000000-11111111 256阶
- 因为有三个通道 所以有2^(8*3)种颜色 真彩色 32位多一个alpha灰度通道
- 人眼可分辨1000w种颜色 24位图像可存储1600w颜色 但更多色阶有利于后期处理
- JPEG跟TIFF文件每个通道只能分别存8位与16位

## 锐利度

- 描述图像清晰度 由锐度与分辨率决定
	- 锐度描述边缘清晰状况
	- 分辨率描述相邻单元的区分度 传感器决定
- 锐度受颗粒度影响 低颗粒度更柔 高颗粒度更锐
- 远近 稳定性均影响锐度

## 图像噪声

- 信噪比
- iso 高的噪音高
- 类型
  - 固定模式噪声 长曝光跟温度影响
  - 随机噪声 受高iso跟曝光时长影响
  - 波段噪声 受传感器影响 跟白平衡有关
- 模式
  - 黑色高白色低 胶片相反 
  - 曝光不足噪声高 过曝噪声低
- 影响因素
  - 颜色波动
  - 亮斑
- 频率 高频噪点比低频更易接受 振幅也有影响 可通过RGB直方图标准偏差判断
- 通道影响 Bayer排列
  -蓝通道噪音最高
  -绿通道噪音最低
- 像素高底小噪音高 跟电子降噪技术也有关系

## 动态范围

- 最大最小的明暗范围
- 强反射与不平衡的直射光场景需要较大的动态范围
- 照度与亮度相关 光质决定
- 感光元件决定单个像素的容忍度 更大的像素尺寸容忍度更高
- 有些相机低ISO是通过抛弃高光部分实现的
- 低ISO层次更强
- 2的n次方表示几档的光变比
- 相机 扫描仪 显示器 打印机的动态范围不一致 
- 人眼24档的动态范围 相机6-8档左右 红色低蓝色高
- A/D转换 模拟信号转为数字信号 相机使用10-14位A/D转换信号 但一般就能转化出5-9档
- 记录动态范围与展示动态范围是要去别对待的

# 高级概念

## 传感器尺寸

- 尺寸
  - 全画幅 35mm胶片尺寸
  - 中画幅
  - 大画幅
  - APS-C 
  - 43系统
- 切割因子是对角线距离跟35mm对焦线的比值
- 镜头的中心部分成像质量好 存在边缘模糊 越大光线使用率越高
  - 传感器尺寸越大 相同视角焦距越小 越小越广角 边缘成像越差
  - APS-C 23mm焦距相当于35mm 转换倍数1.5
  - 传感器越小 需要镜头越轻便
  - 传感器越大 镜头越沉 成像质量越好
- 景深影响
  - 传感器越大 景深越浅
  - 大传感器需要靠近且长焦 所以景深浅
  - 大传感器人像 虚化背景 因为降噪好 拍风景可考虑高ISO 小光圈
  - 小传感器风景 景深大
- 干涉
  - 大传感器小光圈干涉少
  - 干涉影响分辨率 锐度
- 大传感器 像素尺寸大 噪点少 动态范围宽
- 同样尺寸 同样噪点 噪点一般为高频  像素越多 高频影响越小 成像越干净
- 生产上大块传感器质量要求更高 更贵
- 有些镜头配特定传感器
- 相同景深 大传感器分辨率不占优势
- 同样敏感度 大传感器曝光时间更长
- 像素越大 动态范围大 噪点低

## 干涉

- 艾里斑 2D干涉
- 影响分辨率
- 颜色影响 波长越小 干扰越小
- 同样面积像素越多 干涉越大
- 有些像素矩形 所以会向一个方向偏
- 间隔中干涉要考虑微棱镜
- 干涉并不总是圆形 有时5-8边形
- APS-C在F16会有明显干涉
- 小光圈虽然有模糊 但可表现动态模糊与长曝光流水
- 分辨率
  - 绝对分辨率
  - 人眼分辨率

## 相机vs人眼

- 可视角度 40-60度 50mm标准镜头
- 焦距对比
  - 眼睛是曲面
  - 中间视场比边缘视场细节更多
- 分辨率与细节
  - 人眼60度 分辨率大概500w-1500w
  - 人眼识别特定模式 如脸 引起注意
  - 不对称 视线下方比上方更引起注意
  - 低光下眼睛识别单色 边缘更引起注意
  - 人眼在识别某些模式上放大后缺失 跟相机最大不同 反直觉
- 敏感度与动态范围
  - 人眼动态范围一般10-14档
  - 相机5-11档
  - 灵敏度人眼星空适应后晚上500-1000 白天1
  - 低光环境人眼灵敏度好一些

## 理解超焦距

- 在超焦距上对焦可获得从超焦距一半距离到无穷远都清晰的图片
- 为了照顾前景中景与背景
- 无穷远景深最近的一点
- 跟光圈有关（景深）23mm F5.6 5m
- 经验对焦在场景的1/3处
- 超焦距要注意构图及主题
- 注意相机的景深标尺

# 相机种类与配件

## 单反 vs DC

- 单反特征
  - 取景器
  - 可换镜
    -可用特殊镜头
    -画质好
    -光圈大
  - 传感器

## 三脚架

- 使用时机 安全快门 焦距的倒数
- 全景 合成HDR 动画 合成场景 运动场景
- 选购三脚架
  - 稳定性好
  - 重量
  - 个人负担
  - 支架数
  - 最大高度 越矮越稳
  - 收缩长度
- 云台 vs 滚轴头
  - 云台可单独控制两个方向
  - 滚轴头可一次控制 但不一定稳
  - 强度重量比
  - 气泡水平仪
- 三脚镜头支架
- 桌面三脚架 视线越低出图好
- 铝 碳纤维三脚架（湿环境用）
- 独脚架 运动场景 轴线平面动态模糊

## 闪光灯

- 闪光灯的使用要不留痕迹
- 自然光 人造光
- 光线决定对比度 软光 硬光
- 反光伞反光后柔光 光照度下降
- 半透明塑料板 室外没用 室内有用
- 过分散的光没有对比度 二维化 相机自带闪光灯有这个问题
- 离机闪光灯背对物体效果会好
- 闪光支架效果会好 可消除红眼
- 辅助闪光灯 消除暗影区 减少对比度 耗电多
- 红眼 闪光瞳孔放大 眼底血管尽显 拍照时不要看闪光灯 事先闪光 离远一点
- 电子去红眼效果不一定好
- 闪光白平衡 矫正闪光带来的白平衡失真
- 闪光曝光流程
  - 自然光与闪光两个曝光 有个预闪光评价自然光
  - 闪光时间短于快门 属于曝光阶段中的一部份
- 闪光比
  - 闪光与环境光的比例
  - 总光与闪光的比例
  - 1:8-1:2 效果好 弱闪光 长曝光 作为补光
- 闪光曝光模式
  - 自动 测光快门低于1/60s启动闪光 快门固定1/60 闪光强度取决于明暗程度的测光
  - 程序 一直开闪光 作为补光 低于1/60s同自动模式
  - 光圈优先 闪光比不超过1:1进而延长曝光时间
  - 快门优先 最大光圈不够用时启用闪光
  - 手动 自己调
  - 不能用会闪烁
- 闪光曝光补偿 
  - 每一档表示一倍 
  - 曝光补偿同时影响自然光与闪光
  - 保持或改变闪光比要先调闪光曝光补偿 然后计算曝光补偿 1/3一档调整
  - 提高闪光比需要增闪光补偿一档 减曝光补偿-1/2--2/3档
  - 降低闪光比需要减闪光补偿一档 增曝光补偿1/3-1/2档
- 闪光测光
  - 环境光测量 反射直射不分 婚礼摄影黑白对比高 更容易出错
  - 闪光测量 距离影响最大 近亮远暗
  - 使用闪光曝光锁定而不是自动曝光
  - 不同机器要事先熟悉
- 一次二次曝光同步
  - 处理动态模糊 闪光在前 模糊在后会导致逆向运动
  - 二次曝光会增强动态模糊效果
  
# 镜头

## 广角镜的使用

- 概述
  - 焦距小于35mm 视角大于55
  - 超广角 小于20-24mm
  - 用于贴近 容纳更多景物
- 广角透视
  - 近大远小
  - 变形夸张
- 汇聚光线 调整汇聚点在地平线位置 上下会产生不同的倾斜效果
- 引导线效果 建筑会夸张高度
- 内部或封闭空间 广角包容性
- 偏振滤镜 广角用偏振会导致饱和度不均
- 广角控光 不均的光环镜 渐变中灰密度镜
- 广角镜与景深 与长焦镜景深一致 与使用习惯有关
- 使用
  - 离前景近一些
  - 远近景搭配
  - 透视效果 引导线
  - 边缘失真

## 长焦镜的使用

- 概述
  - 中度长焦70mm 全长焦135mm 视角小于15
  - 长焦会压扁 使物体扁平化 距离压缩
- 远物近化 测不准原理 小视角画框 强化雾气影响
- 浅景深对焦
- 长焦需要短曝光来缩短机身摇晃

## 移轴镜的使用

- 概述
  - 移轴可使视角变宽 倾斜可改变焦平面位置进而改变景深角度
  - 镜头成像圈大 等焦距画质好 
  - 中度望远镜移轴形成全景 扩大视角
  - 移轴镜优化边缘成像质量
  - 相比同等光圈焦距 移轴镜更重且成像质量更好
- 透视控制
  - 远点在地平线上 所有线都垂直地面
  - 移轴会削弱垂直透视效果 使建筑更高耸 更突出 对焦点在地平线之上
  - 普通相机可考虑剪裁或ps
  - 移轴镜头优于数码移轴
  - 全景拼接上移轴拼接用的更少 传感器小更易移轴拼接
  - 视角控制上移轴等效焦距会更小
- 景深控制
  - 沙姆定律 传感器平面 焦平面 影像平面汇聚到一点可得到全面清晰的图像
  - 倾斜可使景深成条带状
  - 对焦采用试错的方法

## 微距镜的使用

- 放大率 传感器与真实物体大小
  - 焦距 长焦
  - 对焦距离 近
  - 严格讲1：1 不严格可放宽到1：10以下
  - 传感器越小 像素越高 对小物体放大效果越好
- 对焦长度与有效光圈
  - 越是放大 镜头离传感器就越远
  - 进光少 有效光圈越小 景深变大
  - 1：1放大比有效光圈缩小两档 曝光时间要延长
  - 影响自动对焦与取景
- 微距景深
  - 独立于焦距
- 微距衍射
  - 平衡处理
- 工作距离与焦距
  - 焦距越大 工作距离就可以远
  - 不干扰被摄物
- 外接管
  - 用于长焦镜
- 闭合滤镜
  - 用在镜头前 屈光镜
- 其他方法
  - 望远倍率镜
  - 波纹管
  - 反接镜头环
  - 裁剪照片
  
## 棱镜耀斑

- 长相 5-8边形 降低对比度
- 产生原因 快门形状与棱镜间反光 视角外强光源
- 遮光罩
  - 花瓣型优于圈型 考虑感光元件
  - 可调波纹管
- 棱镜类型影响
  - 定焦好于变焦
  - 广角镜设计会考虑并添加涂层
- 消除方法
  - 纳入光源
  - 引入遮挡物
  - 减少镜片数

## 镜头MTF、分辨率与对比度

- MTF表示固定分辨率下降随距离镜头中心距离的变化
- 线粗细表示对比度大小
- 线颜色表示光圈大小
- 线型表示散光方向
- 一般f8分辨率较好
- 不同品牌计算方法不一样

## 滤镜

- 偏光镜
  - 减少炫光与反射，天更蓝
  - 减光，相当于减少2-3档光圈
  - 线性或圆形偏光镜，圆形适用单反，线性不适合
  - 广角镜中使用有极化现象
  - 日落与彩虹可能因偏光而消失
  - 不平玻璃出现偏光彩虹，飞机上出现
- 中灰密度镜
  - 平滑水流
  - 强光下大景深
  - 减少干涉
  - 让流动物体模糊
  - 增加动态模糊
  - 必要时用，减光很强烈
  - 提高动态范围与本地对比度
- 渐变中灰密度镜
  - 使用明暗变化剧烈场景，如日出日落
  - 考虑光暗变化的剧烈程度
  - 拍摄时考虑位置，强度与透明度
- 雾镜或UV镜
  - 胶片年代UV影响对比度
  - 数码时代主要起保护或保值作用
- 冷暖镜
  - 转换白平衡
  - 数码时代不太需要

## 关心相机与照片

- 传感器灰尘
- 存储照片 DNG格式？
- 光盘5-10年或50-100年
- 硬盘磁头可能损坏
- 磁带便宜可用，适合大数据量，也会去磁去电
- 不断复制会失真，需要RAID保存，校检与修复过程
- 保护版权
  - 隐藏层
  - 分片段
  - 锁右键
  - 用flash展示
  - 水印
  - Digimarc
  - 数码相框
  - 版权协议
  - 相似图片搜索
  
# 数码照片后期处理流程

## 概述

- 白平衡
  - 色温
  - 偏色
- 曝光补偿与恢复
  - 图像柱形图
  - 远看容易判断曝光
  - 极端色调
  - 限制 如低光噪点
- 噪点还原
  - 高ISO使用
  - 具有专门除噪点软件
- 镜头矫正
  - 光晕
  - 变形
  - 色散
- 细节
  - 锐化
  - 局部对比度
- 对比度
  - 强光会降低对比度
  - 过高会导致不真实，颜色过饱和
- 矫正剪切
  - 拉伸
  - 剪切
- 精细化
  - 色彩
  - 选择增强
- 缩放
  - 不同用途不同缩放
  - 保留原始样本
- 外放增强
  - 选择性优化输出图片
- 其他
  - 存储
  - 显示器矫正
  
- gimp colors-levels 手动寻找白点，灰点，黑点或自动，可以按照各个通道调节色阶分布，使三原色向中间靠拢，整体就不会显得偏色
  - gimp colors-color balance 调节颜色平衡
  - gimp Color Temperature Plugin 调节色温值
  - [网络教程](http://spencerrf.blogspot.com/2009/06/gimp_08.html)