---
title: "Causality for Policy Assessment and Impact Analysis"
author: "yufree"
date: "2015/1/5"
output: slidy_presentation
---

## Introduction

> "Impact assessment, simply defined, is the process of identifying the future consequences of a current or proposed action.” (IAIA, 2009)

> “Policy assessment seeks to inform decision-makers by predicting and evaluating the potential impacts of policy options.” (Adelle and Weiland, 2012)

> “... I see no greater impediment to scientific progress than the prevailing practice of focusing all our mathematical resources on probabilistic and statistical inferences while leaving causal considerations to the mercy of intuition and good judgment.” (Pearl, 1999)

## Causal Information

### Target

> practical framework for causal effect estimation in the context of policy assessment and impact analysis, and in the absence of experimental data

### Causal sources

- Causal Inference by Experiment: Randomized experiments
- Causal Inference from Observational Data and Theory: Existing data or Big data

### Identification and Estimation Process

- Causal Identification: domain knowledge based
- Computing the Effect Size: Bayesian networks

## Theoretical Background

### Potential Outcomes Framework

- $Y_{i,1}$ Potential outcome of individual i given treatment T=1 (e.g. taking two Aspirins)
- $Y_{i,0}$ Potential outcome of individual i given treatment T=0 (e.g. drinking a glass of water)
- individual-level causal effect (ICE) 
    - $ICE=Y_{i,1} −Y_{i,0}$
- average causal effect (ACE) 
    - $ACE = E[Y_{i,1}] −E[Y_{i,0}]$

### Causal Identification

- $Y_{i,1}$ (treatment) and $Y_{i,0}$ (non-treatment) can never be both observed for the same individual at the same time
- Association S 
    - $S = E[Y_1|T = 1] - E[Y_0|T = 0]$
- S is not the **same** with ACE
    - association does not imply causation
    - randomized experiment

#### Ignorability

- $(Y_1,Y_0) \upmodels T$ $Y_1$ and $Y_0$ must be jointly independent  of the treatment assignment
- $(Y_1,Y_0) \upmodels T|X$ for realobservational studies, conditional on variables X, $Y_1$, and $Y_0$ are jointly independent of T, the assignment mechanism
- $ACE|X = E[Y_1|X] - E[Y_0|X] = E[Y_1|T=1,X] - E[Y_0|􏰀T = 0,X] = E[Y|􏰀T = 1,X] - E[Y|􏰀T =0,X] = S|􏰀X$

#### Assumptions

- Causal inference requires causal assumptions

## Methods for Identification and Estimation

### Directed Acyclic Graphs(DAG) for Identification

- DAGs Are Nonparametric
- A Node represents a variable in a domain, regardless of whether it is observable or unobservable
- A Directed Arc has the appearance of an arrow and represents a potential causal effect. The arc direction indicates the assumed causal direction, i.e. “A→B” means “A causes B.”
- A Missing Arc encodes the definitive absence of a direct causal effect, i.e. no arc between A and B means that there exists no direct causal relationship between A and B and vice versa. As such, a missing arc repre- sents an assumption

### Indirect Connection

- A causes B via node C
- $A \nupmodels B$ and $A \upmodels B|C$

### Common Cause

- C causes both A and B
- $A \nupmodels B$ and $A \upmodels B|C$

### Common Effect

- C is the common effect of A and B
- $A \upmodels B$ and $A \nupmodels B|C$

### Example: Simpson’s Paradox