---
title: "常旅客攻略"
author: "Yufree"
date: "2016年4月16日"
output: html_document
---

> 本攻略是对我所了解的常旅客信息的一个汇总，一来方便形成体系，二来让更多人了解常旅客并过的更明白些或者说更生活化些。

## 概述

> RULE 1: 刚需为王

常旅客概指商家提供的[用户忠诚计划](https://en.wikipedia.org/wiki/Loyalty_marketing)(customer loyalty program，CLP)，包括但不限于酒店、航空及信用卡等领域。商家设立常旅客计划可以用高级用户优惠或权益来使用户长期稳定使用自己的服务或产品。这是一种营销策略，商家发现优质客户要比普通客户带来更多的利润而相应的CLP可以留住这部分客户。而所谓的CLP是一种层级化的奖励制度，用户忠诚度越高，获得的奖励越高：经常光顾一家商店刷脸，自然服务态度就更好；反之一视同仁，那么竞争对手只要好一点客户就会流失。对于顾客而言看似是区别对待，但是也算是各有所需：因为你没有刚需天天光顾一家商店，那么商店提供的服务也就感觉不出好坏，甚至连名字都记不住。同时我们会发现，实行CLP的行业一般为服务业或运输业，利润率都比较[可观](https://xueqiu.com/4206051491/22279151)，大概10%。由于不那么对应资源或靠天吃饭，所以价格可波动范围比较大。普通客户可能就合作一次，所以价格高低也无所谓或就选价格低的而不在意品牌。常旅客会想通过长期稳定的合作来拿到平均较低的价格与相对优质的服务，此时CLP就可以起到这个作用。总体来说，CLP有利于商家品牌溢价的实现与忠诚度的提升；而对有较高需求的常旅客而言，CLP实际也节省了部分开支并提升了体验；对普通旅客而言意义不大，假设你一年乘坐一次飞机，那么一辈子也别想兑出一张里程票。然而，因为竞争与新兴市场的存在，商家总想获得更多的客户来盈利，为此会对自己家的clp搞活动来刺激客户消费。如果你恰巧也有需求，那么恭喜你，后面的内容可能会让你受惠于clp。毕竟如果你打算改善生活体验，clp可能是最方便快捷的。但一定牢记，消费要根据需求与自己的经济状况来才能相得益彰，你也可以创造性消费或体验性消费，但不要太感性消费，这样就不是玩clp而是被clp玩，那样就成了给商家送钱或反薅了。我们可以把clp看成用户与商家博弈的战场，下面，开战！

> 现代用户忠诚计划最早是出现在1981年美国航空公司的常旅客计划。

## 常旅客信息来源

> RULE 2: 建立自己的信息收集体系

关于常旅客的入门与基础知识我们可以直接从网上获取而常旅客相关信息有两个主要来源，一个是商家自己，另一个则是客户组成的clp爱好者论坛或博客。商家自己是最准的，但clp爱好者给出的介绍可以更多的解读出一些幕后信息。同时，来自爱好者的经验往往也可以帮助我们站在别人的肩上望远与学会一些行话或装腔的态度，毕竟我们可都是要成为玩转clp的玩家！

先说官方，当你要使用某个商家服务时，一定查一下商家有没有对应的clp。具体的形式包括但不限于用户俱乐部、积分累积兑换体系、商家联盟等。如果有的话就注册一下，一般而言注册门槛与入门服务质量成正比。此处有的商家会把门槛提高甚至要收费，但一般而言他们的目标客户对于注册门槛可能根本就不在乎；另外有些商家的门槛非常低，低到随手就可以注册，但可能没啥权益，只有累积到一定程度才能开始受益。如果商家提供网页注册的话，一般会问你是否用邮件订阅优惠信息，我建议你钩上。我当然知道你不会去看，但钩上会让商家感觉你有消费欲望而他们能赚到钱，这样有些定向优惠就可能给你。

再说论坛或博客，其实clp爱好者嗅觉都很灵敏，他们对于官方信息都十分关注，一旦出现不错的消息他们会第一时间放出来。这样我们可以把他们当成人肉信息过滤机来快速获取干货。对于论坛，多翻精华帖可以快速学习基础知识，而高热度的帖子里往往有干货。对于博客，一般会有个热点文章什么的看那些就够了。当你完成了基础知识的原始积累就可以每天扫扫新帖子了，这时候我推荐你用rss订阅，每天10分钟浏览下可省去很多事到临头的惊慌。

下面给出五个clp论坛，三个中文两个英文，如果你打算进行知识的原始积累去这五个论坛的任一个就够了。我个人目前常驻3798。

[FlyerTalk](http://www.flyertalk.com/)：世界最大的常旅客论坛与资讯站，很官方

[InsideFlyer](https://insideflyer.com)：之前叫做MilePoint，与上面那个互为竞争对手

[飞客茶馆](http://www.flyertea.com/)：国内最大的常旅客论坛与资讯站，很官方

[3798](http://www.3798.com/)：玩在当下，与上面互称隔壁，重视分享，不触犯法律都可以讨论，路子一般比较野，与飞茶互相鄙视

[我爱卡](http://www.51credit.com/)：信用卡玩家论坛，有个隐藏板块有很多干货

博客就比较杂了，下面是我看的博客：

[freddie奖](http://freddieawards.com/)：每年优秀的clp都会来参与这个评比，你可以根据得奖情况选择自己打算使用的项目

[BA](http://boardingarea.com/)：群博，里面有多个专栏荟萃，也有中文的

[LL](http://loyaltylobby.com/)：更新较快，更专注酒店与航空

[TPG](http://thepointsguy.com/)：提供点数估值，但因为已经被收买，不用太当真

[美国信用卡指南](http://www.uscreditcardguide.com/zh)：中国留学生做的，关注信用卡

[刘总](http://tmtravelworldcn.boardingarea.com/)：中国常旅开拓者，目前在创业，博客已经不怎么更新

[张磊](http://www.wanzaidangxia.com/)：曾出版《玩在当下》，目前搞p2p去了，但博客也在更新

[飞常旅客](http://www.verylvke.com/)：关注英国常旅信息的中文博客

[研究生](http://www.pointsjourney.com/)：台湾博主，内容系统

[非常玩家](http://www.veryers.com/)：界面山寨3798，似乎是某个版主

[常客说](http://www.changkeshuo.com/)：高端圈子，进不去也不太想看

此外还有些公众号，我知道的多是来自论坛里的玩家，很多订了也不看，重复率比较高。

## 常旅客术语

- [常见术语](http://www.veryers.com/creditcard/1741.html)

- [北美常见术语](http://travelafterwork.com/2015/08/20/%E6%96%B0%E4%BA%BA%E5%BF%85%E8%AF%BB%EF%BC%9A%E8%96%85%E7%BE%8A%E6%AF%9B%E8%88%AA%E7%A9%BA%E9%85%92%E5%BA%97%E5%BF%85%E5%A4%87%E7%BC%A9%E5%86%99%E5%92%8C%E6%9C%AF%E8%AF%AD/)

- [航空术语](http://www.3798.com/archives/89.html)

## 返利专题
## 匹配专题
## 积分专题

酒店，航空与信用卡的clp都可以看作一种虚拟货币，但跟真实货币相比他们的流通范围是有限的。其实这倒是很多品牌建立clp的初衷，通过积分与晋级体系让用户忠实于自己的品牌，对于用户而言较少的选择实际也方便了决策还能获得一些奖励，何乐不为。那么，如何最大化的利用积分呢？这里先计算下积分价值，搞明白消费的回馈究竟在哪里。

首先我们来看一个简单场景：熊大打算外出旅行，打算坐飞机住酒店。他每花1000元机票会通过联名信用卡获得50里程，每花1000元酒店会获得100酒店积分。假如10000里程价值500元，相当于机票回馈0.25%；酒店大概10000分价值500元，那么酒店回馈0.5%。那么是不是这个场景下酒店更值呢？别忘了飞机本身也累积里程而酒店也累积积分，这个是大头。以京沪线为例，1000元机票大概1000里程，此时航空回馈达到5.25%；而住一次酒店也可能产生1000分左右的酒店积分，酒店回馈达到5.5%，这样是否就这些了呢？别忘了订酒店跟机票可以通过返利网站购买，一般酒店能给到5%-8%而航空只能给到2%-4%的返利。别忘了信用卡有的本身也自带返利，但这部分我们刚才已经算到联名卡的回馈里去了，如果你没有联名卡，银行回馈差不多也就是0.2%左右。那么这样一次出行下来我们理想条件下可以拿回约8%左右的回馈，注意此时并不考虑酒店、银行与航空公司的活动，也就是说如果你会花钱，正常消费就跑赢cpi了，市面上8%的理财基本都p2p了。总结下，公式如下：

回馈＝返利网站返点＋信用卡刷卡积分＋航空公司里程＋酒店里程＋其他

那么如何提高积分价值或者说获得更高的反馈？我们看下公式。

第一项，这个返点有的是按开支比例，有的则是按消费次数。那么很简单，前面那个没有多少套利空间，后面这个如果商家没算好就惨了，卖vps的网站经常在返利网站搞活动，然后就被薅羊毛了，特别是那种首次消费不论金额多少一律返的简直就是给人发钱。

第二项，这个就看银行活动了。目前国内银行特别鼓励海外消费，经常给免掉货币转换费与手续费等等，积分上也给的很大方，经常就是两倍三倍，动不动还搞个10%左右的返现。如果你10%返现买了50-10的礼品卡，这个套利空间足够大了，特别如果你能45把礼品卡卖了，那就是利用信息差纯赚了。不过银行也不傻，这类活动都有上限，意思意思拿个零花就算了。制造消费本质上是一种变现渠道单一的预付息的储蓄，没有转化渠道要慎重去玩。

第三项，目前国内这几家竞争都够激烈的，热门航线能赚但冷门航线都出现了强迫公务员买机票的政策。不过目前一个趋势就是航司不太想让代理赚钱了，第三方平台或代理人都是有返点的，如果都到官网来自然就减少开支了，那么航司势必舍得投钱教育市场。这场没有硝烟的战争在移动端上打得正酣，不过你若舍得时间，自然可以找到新航线多倍里程或淡季优惠这类活动，如果有需求自然稳赚。信用卡航空联名卡还是要有的，可预防有些航司的里程过期。此外，高端信用卡的积分也可以很好的比例转为里程，值得拥有。

第四项，大的酒店集团一遍都会以季度为单位推出活动，返回的大都是积分，要重视积分的有效期与累积效率。如果你不打算只玩一个酒店集团，建议把积分改成累积里程并参加多倍里程活动，这样很快你就可以兑出一张票了。酒店联名卡也很有必要，不过也看情况，其实酒店权益也可通过高端信用卡品牌获取，这样自由一些。

为什么会有其他？因为积分体系最常见是酒店航空信用卡，但其他第三方或平台也会有自己的回馈计划，例如连锁商场、餐馆、邮轮或租车公司，同样一笔钱可以从现金变储值卡变积分最后变成消费，每轮转一次都可以拿一次回馈，这么玩都在规则内，没有风险，这也是礼品卡套利的本质。

从公式上我们可以看出，同样一笔钱可以通过附加信息来提高价值，在消费这件事上处理信息的脑子决定了钱的含金量而不是面值。然而，脑力活动本身也是一种精力与时间的消费，玩玩就可以，不要沉迷，不行找贩子出点手续费得到的回馈也是白赚的。

下面再说下商家设立积分制度的立意。一般而言，成熟市场增长率都是个位数百分点，积分本质是抢夺两类用户培养一类用户，第一类一般都是给报销的，对价格不敏感，这类用户叫商务用户；第二类就是不差钱的豪了，良好的服务历史可以让他们继续掏钱或者给协议价；第三类要培养的就是那些散户或新户。这三类都能带来高收益，其余的基本都是薅毛的了。对商家而言如果每次市场行为吸引进来的都是薅毛的，那么利润摊薄积分就会贬值，但是如果大都是新户那就赚了，国内目前正是一个新户多于羊毛户的市场，所以有时候套利空间会不可思议的大。与此对应的是积分其实是商家发行的货币，自己可以定价也可以贬值或扩大适用范围。所以说理想条件就是你不要持有太多积分或者选择性持有那些可以转化，用法更像货币的积分。国外有四大积分体系，国内能玩上的只有spg，还被万豪给买了。这里面一个关键点就在于货币要能流通才叫货币，你有10000分楼下小卖部积分但小卖部只卖零食你又不吃零食，那不管这10000分多么便宜，你持有了都是亏的。同样你不坐飞机累积里程就没啥意义，不住酒店累积积分也没啥意义，信用卡比较特殊，积分一般可以变现成权益，所以优先累积的应该是信用卡，花同样的钱获得更好的服务比变现更有实际意义。当然里程积分也可以换礼品或权益，但比例一般都比银行坑。别忘了积分的解释权在商家，如果不能把积分很快变成权益，那么一旦过期商家就高兴了，相当于你存了钱，然后钱变成纸了。如果你懒得搭理这些事倒是可以参与一些第三方平台的clp，把回馈放到一个池子里，这样流动性也就高了。并不是说第三方没有价值，相反，第三方可能更适合此类消费不大但有回馈诉求的人，这个基数可能不小，他们参加单一公司的clp实际是亏的，这里亏的可能不是钱，而是选择的自由与不用保级的轻松。

最后说下一个非出差人士的clp基本策略。一年一次家庭旅游5-7天左右，两到三次2天左右的旅游。也就是一年产生的房晚大概在10晚左右，酒店方面可以考虑保个金卡，每年兑两三天的高端免房出来，甚至直接通过高端信用卡享受权益。里程靠刷卡与买里程活动基本可以保证全都是里程票出行，因为非出差的话假期都是旺季，里程票就是经济舱也划算。这样就可以完全当自己正常消费，每年目标就是给自己度假换个票加酒店，积分玩多了伤神，顺水推舟最佳，要大概知道活动值不值得参加，该出手出手就可以了。最好把一年到两年设定为一个周期，周期内的积分可以变现，长了就没意思了，相当于买了商家的垃圾债。

## 羊毛专题

- [查询协议价 ](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=61653&fromuid=26550)
- [Rocketmiles新用户首次预订得美联航里程](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=58444&fromuid=26550)
- [sprint新用户活动0.004美元／1AA里程](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=69144&fromuid=26550) 
- [choicehotel新用户潜在的1.1cpm买AS,AA,UA里程方法](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=46834&fromuid=26550)
- [利用Sears降低差旅费用 注册后用打折的Gift Card付款](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=68052&fromuid=26550) 
- [航班延误险大全](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=34714&fromuid=26550)
- [Priceline实战经历](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=3517&fromuid=26550)
- [信用卡卡号生成器](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=13049&fromuid=26550)
-  [支付宝无限提款](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=7895&fromuid=26550)
- [北美租车折扣码](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=542&fromuid=26550) 
- [美签技巧](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=17550&fromuid=26550) 
- [TCB UK 赌博羊毛](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=12005&fromuid=26550) 注意防沉迷
- [礼品卡攻略](http://www.3798.com/bbs/thread-13441-1-1.html)

## 第三方专题

## 酒店常旅客

### spg

以下来自公众号[爱浪客](http://mp.weixin.qq.com/s?__biz=MzI3ODE3NzQ1Mw==&mid=2651658393&idx=1&sn=4b82aead86448e56d1ab4f5fcdd2b239#rd)

- 新注册促销，如果你还不是SPG会员：

被推荐后 30 天内、点击邮件中链接注册、60 天内完成一次符合条件的住宿，都可获得 1000 点积分。

网址：https://www.spgpromos.com/dashboard/site/
飞茶网址：http://www.flyertea.com/portal.php?mod=spginvitation&id=117323（过期）

- 新人促销

输入你的会员号看能拿到哪一种促销，包括不限预订渠道住二送二、APP预订的住二送二、住两次7500分、住两次4000分、住两次积10晚等。
注意：下面链接的尾数6可以换成2、3、4、5试试：）

网址：https://spgpromos.com/selectmemberexclusive6

新人jumpstart抽奖

需要注册，面向亚太区，给新人的，老用户是邀请，感兴趣可以去邮箱要一下时间：2016年4月15日~2016年9月15日
活动内容：注册有机会200分，花10刀有机会拿1300分，下载spg手机应用有机会500分，预定一晚有机会2500分，注册keyless有机会500分，每个活动抽200人
网址：https://www.spgpromos.com/jumpstart

- 欢迎分

每次入住，金卡250积分、白金卡500积分欢迎积分。Design Hotels设计酒店也有250、500欢迎积分。
在有的酒店，欢迎积分、欧陆式早餐或当地礼品3选一。
网址：http://www.starwoodhotels.com/preferredguest/about/index.html?categoryId=brand.benefits.overview

- “Make A Green Choice(绿色之选)”计划：

无论以何种价格（包括但不限于C+P、积分兑换）入住，只要酒店参加该活动，住2晚以上都可以选择参与。亚太区参与“Make A Green Choice”计划的SPG酒店统一调整为每晚250 Starpoints积分。鼓励续住房客选择“免除客房清洁”服务，只要房间内保持整洁，可自愿决定是否需要撤换床单、洗涤被套等服务，以节省大量的水资源和能源消耗。

- 新开业促销：

入住拉美地区指定9家新开业酒店，每一次住宿赠送早餐和1000积分。
网址：http://www.latin-america.starwoodoffers.com/newhotelopenings

入住亚太地区新开业酒店，可享受双倍积分、早餐等额外奖励和优惠。
网址：http://starwoodpromos.com/openingoffers-new/cn

- 套房促销

在参与本活动的喜达屋酒店，入住套房将获得3000分的奖励。
网址：http://www.discoverstarwoodsuites.com
注意：3000分约价值600元，所有有时候直接定套房也很好。

- 召唤神龙

2016全年住满11个品牌，奖励11000分。

- 地区促销

1）入住下列Mexico, the Caribbean, USA 参与本活动的喜达屋酒店两晚及以上，每次住宿可获得1000里程。
网址：http://latin-america.starwoodoffers.com/clubpremierbono/en

2）万事达卡预订及支付参与计划的酒店和度假村，在欧洲/中东/非洲地区可买两晚、送第三晚。
网址：http://www.eame.starwoodoffers.com/eamemastercard/cn/multibrand
  
3）在参与本活动的喜达屋酒店（北美/拉丁美洲地区），入住两晚及以上可享第2晚六折。
网址：http://www.americas.starwoodoffers.com/bettertomorrows
  
4）在参与本活动的喜达屋酒店（欧洲/中东/非洲地区），入住不同房型将获双倍/三倍积分或3000分。
网址：http://www.earnyourdreams.com

5）7月14日前入住亚太区喜达屋酒店和度假酒店两晚，并使用万事达卡付费，即可乐享八折。
网址：http://www.spg-asiapacific.com/save20/cn/

- 卖分 

最高75折，折扣应该历史最高了 

网址：https://buy.points.com/marketing/spg/landing_page/#/en-US（4月15日截止）

- 小秘书代订

除了SPG，喜达屋还推出商务人士(企业)CLP叫SPG Pro（我们一直叫小秘书。一个简单方法就是：请酒店销售或熟人帮你申请，与你的SPG会员号一致，见https://www.starwoodhotels.com/preferredguest/about/index.html?directoryId=spgpro）。现在有两个面向SPG Pro会员的促销：
  
1）使用SPG Pro（旅行代理）为他人订房，在3月14日至6月30日期间完成的住宿，每三次符合条件的预订可获1500分奖励，最高可获15000分。
网址：https://www.spgpromos.com/bonusexpedition
  
2）使用SPG Pro（行政助理）为他人订房，在1月1日至6月30日期间完成住宿，每次符合条件的预订可获得500分奖励，最高可获得10000分。
每在一个城市预订一次符合条件的入住，还能额外获1000分奖励，最高可获10000分。两者叠加获20000分。
网址：https://www.spgpromos.com/cityexplorer

- 抽奖活动
时间：4月30日
玩法：输入SPG会员号，任选一张卡片可随机抽奖。
奖励需在入住拉斯维加斯Tribute Portfolio后方可兑现（每位会员只有一次抽奖机会）。大奖是入住该酒店获得一晚免房，可用于兑换全球Cat1~Cat6的喜达屋酒店及度假村，需7月31日前使用。
注意：各种其他抽奖还请随时关注。
网址：https://www.spgpromos.com/slslasvegas

- 1000分换5折

其实就是SPG50优惠价格，请回忆巴厘岛瑞吉。
支付1000点，在全球大部分酒店(无论CAT级别)的RACK rate给予50% 折扣，可享受最多连续5晚半价。
只能电话预定，需要一个个问你想要订的酒店价格，可激活所有促销活动。
第三方查询网址：http://www.awardpad.com/rate-lookup（输入SPG50）

- Uber积分
没错，乘坐Uber，是可以累计spg积分的。请去关联一下。
网址：https://www.spgpromos.com/uber/

- 购买积分

时间：等下次
玩法：每年几次75折买分促销（配合返利网、境外返利信用卡等），每人每年可买3万分，可以多账户购买后转分。
注意：新会员要在注册后第15天才可以购买。
网址：https://storefront.points.com/spg/en-US/buy 

- 会籍

一夜升金： http://www.spg-asiapacific.com/worldmastercardgold/cn/

SPG商务客plus：https://spgpromos.com/spb

白金挑战：90天入住18晚，需要发邮件去申请。

终身金：250 晚和 5 年尊贵会籍，终身白金：500 晚和 10年白金会籍。预计2018与万豪礼赏合并后会有变化。

礼赞卡
金卡或白金卡保级后，每年有4张、8张礼赞卡，你可以送给酒店员工表示感谢，他们可以积250、500分。
网址：https://spgpromos.com/elitethankyou/

EDM美食卡
Eat Drink and More餐饮计划会员卡，专为吃货准备，瓦力常年备有各酒店集团美食卡。各酒店套卡内容和价格不同。主要是餐饮2人5折，本城市通用。
网址：https://www.eatdrinkandmore.com/

[SPG会籍无限延期](http://www.3798.com/bbs/forum.php?mod=viewthread&tid=30012&fromuid=26550)


- 花积分

积分太多了，你要懂得花！积分有效期12个月，动一下再延12个月。
积分转让、积分换房4送1、积分里程大礼包、积分即时换礼等大招以后再讲。瓦力主要谈谈：

SPG moments 
玩法：SPG提供给会员用积分来竞拍的各种票：演唱会、体育赛事、电影首映门票等等。
SPG在全世界有几个签约的体育馆包厢，包括上海梅赛德斯奔驰文化中心、洛杉矶Staples Center、纽约Madison Square Garden 和伦敦的O2 Arena。同时其他赛事包括美国网球公开赛、迈阿密热火队比赛、有时候还有其他一些餐厅体验，包场给你和你的朋友看电影首映等。有时候非常划算，而且是独一无二的体验。
网址：https://auction.starwoodhotels.com/（有中文版）

积分价值
按照10000分2000块计算

### ihg

- 积分精算 

0.7美分买分，简单说就是先搞到5000分，然后选p＋c方式订房，然后退掉，现金部分就变成分，可以做到70刀10000分。下面链接这个可作为订房标准，对于白版用户，记住65刀cat1，97刀cat2，不过要考虑活动叠加回血

网址：http://bbs.3798.com/forum.php?mod=viewthread&tid=17960&extra=page%3D1%26filter%3Ddigest%26digest%3D1

- match hertz 

Spire Elite级别可得到5星hertz会员

网址：http://bbs.3798.com/forum.php?mod=viewthread&tid=61199

- 亲友价 

预付但没有snp，但就是便宜，定之前对比下第三方

网址：http://bbs.3798.com/forum.php?mod=viewthread&tid=1737&extra=page%3D1%26filter%3Ddigest%26digest%3D1

- 累计里程

如果有多倍里程活动，那么可以考虑将累积积分改为累积里程，例如住HI或HIX，积分很少，但国航里程就可以拿800

网址：http://www.ihg.com/hotels/gb/en/global/earn-rewards/miles?PID=7372891&cm_mmc=CJ-_-4015589-_-7372891-_-DeepLinkRedirect_Gen_IC_Text_ENG&glat=AFFI&icdv=99634975

- pb活动 

5000分预定，可以与上面活动叠加，实现35刀住ihg

### hilton

- MVP（20％） USteam（15%）优惠房价 

- 其他希尔顿活动：http://bbs.3798.com/forum.php?mod=viewthread&tid=78204

### marriott

- 绑定sns 

twitter跟ins关注@MarriottRewards 与@GaylordHotels 每次25分 共100分 用#MRpoints  #MRRedFest发twitter或ins 每次25分 最多10次 这样最多可以600分

网址：https://mrpoints.chirpify.com/mrpoints/register

### hyatt

- match 

只面对spg白金以上会员，发邮件到goldpassport@hyatt.com

### Accor

- 股东福利

51欧持股得到永久金卡

网址：http://bbs.3798.com/thread-56114-1-1.html

## 航空常旅客

### 星空联盟

#### 国航

- 休息室非常好，有沙发床

#### 哥伦比亚航空

- 积分兑换方便
- 有问题可以改

#### 加航

- 态度恶劣

### 天合联盟

#### 南航
#### 东航
#### 达美

- 积分永不过期

#### 大韩航空

- 驾驶技术不好，大飞机颠簸
- 空乘年轻漂亮，会中文，英文听不懂
- 发眼罩、水、拖鞋、毛毯
- 紧急出口无窗，空间大可调

### 其它航空

#### 海航

- 积分不过期

#### 以色列航空

- 多一次安检，通过对话安检，所以经常延误
- 空乘年轻，有酒有娱乐系统，飞机餐是拉比认证的洁食
- 降落后要鼓掌表示敬意
- 不属于联盟

#### 波特航空

- 小螺旋桨飞机冲8 Q400，比较颠簸
- 有小零食，候机的休息处都是免费的
- 两个空乘，两个飞行员
- 托运行李另外收费，随身行李可单独运输
- 下午飞机一般会晚点

### 机场

#### 仁川机场

- 转机免税店活动多
- wifi覆盖好，中文友好

#### 多伦多城市岛机场

- 一个小岛，通过地下通道过去
- 有一个小免税店
- 饮料小吃都免费
- 飞机跑道的终点是湖

## 信用卡

信用卡的成本核算

### 国内

#### 招行

- 任意一笔境外星巴克

#### 浦发

- 8%返利封顶 visa master各一张
- ae白$5返利

#### 中行

- 长城卡储蓄账户取现没有手续费

### 加拿大

#### CIBC dividend platinum visa card

- 买菜加油4%，其余1%
- 租车保险LDW／CDW

## 优惠注册链接

- [Dropbox500MB奖励邀请](https://db.tt/fkiWF5s)
- [印象笔记邀请](https://app.yinxiang.com/referral/Registration.action?sig=109fa04a28ae4b5ce839f68df2627ee3&uid=6379) 国内版
- [Evernote邀请](https://www.evernote.com/referral/Registration.action?sig=1619d3b0402bb3015b6f8141c3e8321a&uid=4305565) 国际版
- [3798](http://www.3798.com/bbs/?fromuid=26550) 羊毛党
- [返利网](http://passport.fanli.com/come?id=129593204&t=4&spm=b.invite.pcoldreg.copy) 5元注册奖励
- [TCB中国](http://topcashback.cn/ref/Member115585738118) 海淘返利
- [TCB美国](http://www.topcashback.com/ref/yufree) 美淘返利
- [TCB英国](http://www.topcashback.co.uk/ref/yufree) 英淘返利
- [Ebates](http://www.ebates.ca/referrer?referrerid=VXorju5nQU4%3D%0D%0A&src=Link)加拿大返利
