---
title: "流行病学精要"
author: "于淼"
date: "2015年2月3日"
output: slidy_presentation
---

## 频率测量

### 风险（risk）

也称作发病率（incidence），表示在一段给定时间里**新增**某种健康效应的比例

$$risk = \frac{new cases}{total individuals at risk}$$

举例：5年风险0.1表示在5年里某个个体有10%的几率出现某种健康效应

前瞻性研究（prospective studies）常用，但控制性研究（case-control studies）里总体风险无法确定，不能使用。

### 比率（rate）

表示在一个人群中某种健康效应出现的速度。单位为每个人年，个人年表示风险个体参与研究到出现健康效应的总时间

$$rate = \frac{new cases}{total person-time at risk}$$

举例：0.1案例每个人年表示对于每10个人追踪1年或2个人追踪5年将会有一个案例出现

### 胜率（odds）

$$odds  = \frac{individuals with the health outcome}{individuals without the health outcome}$$

### 患病率（prevalence）

表示在指定时间里具有某种健康效应的人群比例，非新增

$$prevalence = \frac{affected individuals}{total individuals in the population}$$

举例：患病率0.25表示人群中有25%的人在指定的时间段里受某种健康效应影响

经常会导致因果推断不准，因为影响因素产生的效应被本来的效应覆盖了

## 关系测量

### 风险差（risk difference）

$$risk = risk_{exposed} - risk_{unexposed} = \frac{cases in exposed group}{total at risk in exposed group} - \frac{cases in control group}{total at risk in control group}$$

正数表明对某种健康效应有促进作用，负数表示有抑制作用

### 风险比与比率比（risk ratio rate ratio）

$$risk ratio = \frac{risk_{exposed}}{risk_{unexposed}}$$

$$rate ratio = \frac{rate_{exposed}}{rate_{unexposed}}$$

表示暴露与健康效应的关系强度，1表示无关，但比例关系不能给出绝对差异

### 胜率比（odds ratio）

$$odds ratios = \frac{odds_{exposed}}{odds_{unexposed}}$$

常用在控制性研究里替代风险比或比率比，这时风险比无法计算，但几率比可以在总体效应比较小与特殊采样技术使用的时候近似于风险比或比率比，解释起来与它们一致

### 空值（null value）

表示无效应，对于风险比与胜率比是1，也是对效应进行假设检验的零假设

## 显著性测量

### p值

空假设下某个观测值出现的概率，越小越不容易出现

小于0.05表示统计显著，95％置信区间的边界也用来表示某个点估计是否统计显著

## 准确性测量

### 置信区间

点估计之外描述估计准确性的，95％置信区间表示该区间有95％的概率含有真值，越小表示估计越准确

## 其他术语

### 原始与调节值

有些测定数值受其他因素影响，需要调节，常见的有性别，种族，社会经济状态，抽烟状态与家族历史

## 实验设计

### 随机控制实验（Randomized Control Trials）

研究对象随机分配到不同处理组观察该处理的影响，控制组不处理（安慰剂）或者使用活性对照

随机可避免基线差异，简单随机使用随机数，分层随机可将强的外在影响如抽烟在基线处平衡

随机实验包括临床实验与社区实验，前者用来评价新药的影响，后者评价某种地域政策

伪装指受试，研究人员或数据分析人员对某临床实验的分组知晓情况，受试不知道为单盲，受试与研究人员不知道为双盲，三者都不知道为三盲。用来避免安慰剂效应、后随机混杂（当受试知道分组后会出现行为上的改变而产生新混杂变量）、选择偏误或信息偏误以及患者顺从性。

交叉指在实验过程中将一组受试的处理换为另一组，例如某些效果比较快的处理，也会引入新的偏误。

后续损失指研究进行中某一处理组放弃实验的比例高于另一组，产生分异损失。

### 队列研究（Cohort Studies）

队列研究追踪有相同特征的人群来研究某种影响下的健康效应。

前瞻性队列与回溯性队列，前者关注队列将来发生什么，后者关注发生后的暴露信息，均为纵向研究。

队列选择要确定研究对象与基线，在基线上无效应的进入队列作为风险人群，前瞻性队列在研究开始时确认暴露基线，回溯性研究选取过去某个时间点作为暴露基线。

用不同组的风险值（Risk或Incidence Proportion）、比率（Rate）及风险比（Risk Ratio）评价。

优点：直接测量风险，适合稀有效应，也可以考察单个暴露下的多个效应，适合进行观察性因果研究。

缺点：大样本量，时间长，由于放弃可等导致代表性下降，测定暴露上会引入信息偏误。

### 病例对照研究（Case-Control Studies）

病例对照研究考察暴露与健康效应的联系，从效应到原因评估暴露在不同效应组的比例是否不同，常用来研究稀有案例。

案例对照研究的研究对象是具有某种健康效应的人群，在基线上选择控制健康效应的状态而不考虑暴露状态。

该类研究中整体风险不知道，计算胜率比并估计风险比。

控制组选择是难点，有队列研究时，可以根据研究人群等机会成为控制组进行选择或者在调查结束时从幸存者中采样作为对照或者以新发生案例的剩余人群作为对照（可直接估计风险比）。

优点：适合罕见病研究，采样量小，花费小

缺点：不能估计风险值，存在选择偏误，不适于研究稀有暴露条件

### 断面研究（Cross-sectional studies）

断面研究不考虑时间追踪，仅仅记录某时间点研究人群的健康状态与暴露状态。

记录患病率（Prevalence）或计算患病率几率比（prevalence odds ratio）或患病率风险比（prevalence ratio），前者适合慢性病，后者适合急性病，断面研究更适合来源不明的慢性病研究。

断面研究受暴露生存时间影响，同时与案例对照试验一样难于推断因果关系。

### 生态学研究（Ecologic Studies）

生态学研究以组为单位，可观察暴露因素与健康效应的关系,不区分个人，因此不能进行因果推断。

生态学研究的现象常常因为混杂因素产生谬误，可以是断面跨分组，也可以同群组跨时间，也可以描述时空分布。

## 因果推断

因果推断在流行病学中很重要，但目前没有标准来界定因果而仅仅有一些指南。

### Hill 因果标准

由流行病学家Austin Bradford Hill提出的9条判断因果关系的标准，充分不必要条件，不能作为清单使用。

### 部分原因理论

Kenneth Rothman 提出，认为健康效应的原因可看成一个饼图，缺少任一部分结果都不会发生，用来了解结果的发生过程。

### 逆向模型（Counterfactual models）

考虑无暴露状态下是否产生效应的思路，群组水平考察。

### 有向无环图（DAGs）

概念流程图，考虑混杂因素。

## 诊断评价与筛选测试

用来评价健康状况有无或严重程度。

### 黄金标准

最有效的诊断过程，通常比较贵。

### 测试结果

a代表真阳性，b代表假阳性，c代表假阴性，d代表真阴性。

患病率为(a+c)/(a+b+c+d)

敏感性为Se = a/(a+c)

特异性为Sp ＝d/(b+d)

假阳性为1-Sp

假阴性为1-Se

真阳性预测值为 PPV ＝ a/(a+b)

真阴性预测值为 NPV ＝ d/(c+d)

患病率影响预测值

## 混杂偏误

理解为线性模型中的其他变量，导致估计出现单向偏误，需要Maentel Hanzel方法计算风险比。

### 未暴露人群中存在干扰结果的混杂因素

计算未暴露人群中混杂因素的风险比等数值观察是否干扰，例如抽烟与年龄干扰肺癌。

### 同时干扰暴露与效应的混杂因素

测定暴露与未暴露条件下混杂因素的风险比等数值观察是否干扰，考虑生物学意义。

## 效应修饰（EMM）

指由于另外的变量导致效应分类的状态，例如年龄可能造成某种药药效相反，可理解为线性模型中的交互作用项。测定有混杂因素与无混杂因素下的两个风险比，如果差异很大，则存在修正测量效应，如果影响原始风险比，则要同时考虑混杂因素。

可使用限制，配对，随机化等方法来消除混杂偏误；EMM要分层讨论。

## 信息偏误

无差异错误分类会导致风险比趋近于空假设。
差异错误分类会导致风险比远离空假设，例如回忆偏误，采访偏误。

## 选择偏误

源于选择幸存与追踪损失，志愿者代表性，无响应基线偏误，医院患者偏误，健康工人效应（工人比不工作的人健康）。

