---
title: "中国古代史"
subtitle: "PekingX: 02132750x Ancient History of China"
author: "于淼"
date: "2015年3月19日"
output: slidy_presentation
---

## 中华文明起源

- 古史传说与疑古思潮
    - 顾颉刚：时代愈后，传说的古史期愈长；时代愈后，传说中的中心人物愈放愈大
    - "东周以上无信史"
- 从疑古到释古
    - 文献研究与考古研究相结合
- "夏娃理论"与"亚当理论"：人类来自非洲
- 苏秉琦：新石器时代六大文化区系
- 外来说－本土说
- 一元论－多元论
- 夏商周断代：二里头文化可能是夏文化

## 商代青铜文化

- 前16世纪到前11世纪
- 商朝前期：成汤灭夏－盘庚迁殷
- "国之大事，在祀与戎" 青铜是政治权力
- 鼎等青铜器是通天阶级的政治手段
- 甲骨文清代发现 有刻辞有卜兆
- 一条完整的卜辞包含有叙辞、命辞、占辞、验辞四部分
- 商王亦为宗教领袖 解读卜辞 加强王权
- 国家结构：内外服制

## 西周礼乐文明

- 公元前1046－公元前771年
- 封建制：分封人民土地，建立国家
- 宗法制：嫡长子继承制
- 周公制礼作乐
- 礼制中最重要的莫过于封建诸侯之册命礼
- 张光直：夏商周三代的文化大同而小异。大同者，都是中国古代文化，具有共同的大特征；小异者，代表地域、时代与族别之不同。

## 春秋战国经济

- 井田－小农
- 春秋（BC770-BC476）自周平王东迁洛邑到周敬王卒，因鲁史《春秋》记录了这一阶段的历史而得名
- 战国（BC475—BC221）这一时期各国混战不休，故前人称之为战国。把“战国”作为时代名称，开始于西汉末年刘向汇编的《战国策》
- 西周井田制下，井田中有公田、私田之分。小块私田由每户农民耕种，收获归己，公田则由大家通力合作，收成归国家或贵族
- 铁制农具：铸铁冶炼与柔化技术，提高生产力，青铜较贵
- 《吕氏春秋》中《上农》、《任地》、《辨土》、《审时》四篇，是战国末年农学的代表著作
- "初税亩"：田亩的租税成为君主政权的主要财源
- 国家直接控制全部人口——编户，国家得以彻底掌握、运用人力资源

## 春秋战国政治和军事

- 争霸－兼并
- 春秋：王权衰微、大国争霸 从“礼乐征伐自天子出”到“礼乐征伐自诸侯出”
- 春秋时代战争特点：规模小、时间短、讲究礼节、程序
- 战国时代，政治和战争的目的从争霸转而成为兼并。军队数量扩张，军事行动范围扩大，由步骑兵的野战包围战代替了车阵作战。战争的惨烈程度大大增加。春秋时代战争“文质彬彬”的色彩荡然无存

## 春秋战国政治制度

- 宗法分封－专制官僚
- 世卿世禄－俸禄
    - 在周王畿和各诸侯国内，世袭的卿大夫按照声望和资历来担任官职，并享有一定的采（cài）邑收入
    - 采邑大小主要是由爵位和职务的高低决定的。颁给一定数量的土地及土地上的劳动者。爵位越高，官职越大，他采邑也就越大、越多。世代做官、贵族身份世代保持
    - 俸禄制度：佣徒鬻卖之道《荀子·议兵》
    - 玺符制度：公文用玺、发兵用符、出使用节
    - 上计考课制度：岁终奉其成功，以效于君，当则可，不当则废 《荀子·王霸》
    - 郡县制：县出现于春秋初期，原是国君直接统治的领邑，它和国君分
赏给卿大夫的采邑不同。春秋末年，晋出现了郡，设于地广
人稀的边地，面积比县大，地位比县低。县所不同于卿大夫采邑的，就是县内有一套集中的政治组织和军事组织，特别是有征赋的制度，一方面便利了国君的集中统治，一方面又加强了边防。战国时郡的设置仅限于各国边地，县的设置则很普遍。它们取代了过去贵族的采邑。
    - 郡县长官都由国君任免，不得世袭。郡县领域都由国君控制，不作封赏。郡县组织由此逐渐成为由国家权力直接支配的国土区域，成为各国加强中央集权制的重要步骤
    
## 春秋战国学术

- 贵族－民间
- 孔子之前，教育是贵族专利；孔子之后，有教无类，教育学术平民化
- "士"阶层崛起：战国时期的士，已与出身无关，可能来自贵族，也可能起于微贱，其共同的身份标志是知识、智慧和才能，士成为知识分子的代称。是当时社会上最活跃的一个阶层。游说和从师是士进入仕途的两个主要途径。战国中期以后，各国有权势的大臣多养士为食客
- 百家争鸣：诸子，就是士人中的佼佼者
- 诸子的共识：对君主权力之肯定

## 春秋战国社会

- 世袭－流动
- 春秋：“士之子恒为士”，“农之子恒为农”
- 战国：“士、农、工、商 ”四民社会
- 贵富合一－贵富分离
- 齐民化：封国内分属国君与不同贵族之人民的身分逐渐整齐划一，是封建制崩溃、郡县制建立的历程
- 春秋战国之际，是“古今一大变革之会”，从此废去了以礼制为核心的贵族统治，建立了“编户齐民”体制，开始了走向秦汉以后“大一统”的历史进程。春秋战国时代，是中国古代中央集权的专制君主官僚制国家的萌芽时期

## 秦法家思想与军国主义

- 综合国力主要指一个国家在一定历史时期全部可以动用的物质力量的总和
- 国家能力是指国家实现自己意志的能力，国力强的国家不一定国家能力也强
- 秦国社会具有浓厚的军事化色彩。秦国专制君权较早就发展出了相当高的政治控制和社会动员能力
- 刘文瑞：秦文化具有浓厚的功利和实用色彩。与关东六国相比，它没有严格的宗法约束，缺乏人工的礼义雕琢，具有粗犷、剽悍乃至野蛮的西北风味
- 秦孝公商鞅变法（BC356、BC350）与军功爵制
- 軍爵塑造新社會，好战，标准化，独尊君权
- 梁云：考古发现上，战国时代的东西差别是巨大的

## 秦始皇

- BC221年，当秦王政在位的第二十六年，也就是他三十九岁那一年，六国尽灭，完成了统一大业
- 琅琊台石刻：六合之内，皇帝之土，西涉流沙，南尽北户，东有东海，北过大夏，人迹所至，无不臣者。
- 王初并天下，自以为德兼三皇，功过五帝，乃更号曰“皇帝”，命为“制”，令为“诏”，自称曰“朕”。追尊庄襄王为太上皇。制曰：“死而以行为谥，则是子议父，臣议君也，甚无谓。自今以来，除谥法。朕为始皇帝，后世以计数，二世、三世至于万世，传之无穷。”《资治通鉴》
- 阎步克：发达的军事组织与官僚制度之间，存在着天然的亲和性：在集权制、科层制、分工制、非人格性以及对于效能和纪律的积极追求上，二者所遵循的原则经常是内在贯通的

## 大一统帝制

- 废分封、行郡县
- 中央的三公和诸卿制度，地方的郡县二级制度，奠定了秦以后中国古代王朝统治的基本模式
- 严格的户籍制度和法律制度：法网严密、条目繁杂 轻罪重刑、严刑酷法
- 秦代的兵役制度，男子爵在“不更”以下，年龄在傅籍以上，一生中随时皆有被征兵的可能性。秦国的军队分直属中央的军队与地方武装两部分。秦国的军队是步兵和车、骑兵的混合编队，其中步兵是主要兵种
- 权力合法性的论证——“终始五德”说
- 统一度量衡，修驰道，统一货币
- 周良宵：皇权的加强和神化，郡县制的全面推行，体现专制皇权的官僚机构和各种制度的建立，法律的完备和统一，皇帝对军队控制的加强等等，这些就是专制主义中央集权的主要内容

## 天下苦秦

- 修行宫陵墓，劳民伤财
- 秦帝国的人口，估计在4000万左右，仅阿房宫、骊山陵、长城、南越两疆的人力动员，数量已在900万，连累家属，已经超过4000万，几乎牵动帝国的全部人口
- 秦朝统一后，要彻底清除各地原有价值体系上存在的风俗习惯，全面施行秦的法律
- 陈苏镇：秦之“法律令”与关东文化存在距离，特别是与楚“俗”之间存在较大距离，……由文化差异与冲突引起的楚人对秦政的反感，及齐、赵等地人民对楚人反秦战争的同情，是导致秦朝灭亡的重要原因之一

## 汉初王国

- 汉初七位异性王与关东七国接近
- 陈苏镇：郡国并行的本质可能是东西异制，主要意义则是允许或默许东方王国不用汉法，从俗而治
- 在减除异姓王的同时，推行郡县制受阻，便分封同姓王。因功封王——因亲封王
- 诸侯国内，诸侯王享有很大的自主权。《汉书》卷一下《高帝纪》：“自置吏，得赋敛 。” “自为法令，拟于天子”
- 辛德勇：西汉初年，沿承秦制，严厉限制关中与关东地区的人员往来。秦汉时期在地缘政治意义上，有一更为强烈的“关中本位政策”，其核心内容是区别对待关中和关东地区，依托关中，控御关东，特别是中原地带
- 汉文帝：众建诸侯而少其力
- 汉景帝：削藩与吴楚 “七国之乱”
- 汉武帝：推恩令、左官律、附益法。“诸侯惟得衣食税租，不与政事”
- 胡宝国：极而言之，政治上结束战国是在秦代，而文化上结束战国却是在汉代
- 东西并立——南北对峙

## 无为到全盛

- 汉初民生凋敝，黄老无为而治符合现实
- 顺民之情与之休息，躬修节俭，轻徭薄赋，轻刑慎罚
- 汉武帝（BC141-BC87）之功业：加强集权、开拓边疆
- 汉初三公九卿，基本为皇帝服务，宰相相对独立，家天下
- 后提升中朝官与尚书地位，设立尚书台，虽置三公，事归台阁，君主专制
- 设立十三州部监察区与刺史，监督郡太守与豪强
- “以卑临尊”是中国古代监察制度的特点之一，赵翼《陔余丛考》卷二六《监察官非刺史》：官轻则爱惜身家之念轻，而权重则整饬吏制之威重。
- 经济上收回郡国铸币权，设五铢钱，盐铁专营，均输与平准，国家经营商业，用算缗（BC119）、告缗（BC114）向富人收税
- 打击豪强游侠，迁离原住地，任侠的精神凝聚着强固而且广泛的人际结合关系，属于东方传统，危及中央统治，杀郭解
- 《史记 · 游侠列传》：解布衣为任侠行权，以睚眦杀人，解虽弗知，此罪甚于解杀之。当大逆无道。

## 儒表法里

- 罢黜百家、独尊儒术
- 建元五年（BC136），置五经博士。儒家学说被尊为惟一的、官方认可的学说。
- 元光元年（BC134），初令郡国举孝、廉各一人。以儒学为主要考察标准的人才选拔制度——察举制确立。
- 《汉书 · 元帝纪》：汉家自有制度，本以霸王道杂之，奈何纯任德教，用周政乎！
- 萧公权《中国政治思想史》：所不同者，始皇以任法为主，列儒术为诸子之一，武帝尊孔子为宗师，用管商以佐治而已。
- 持续至辛亥革命

## 东汉政治与豪强士族

- 皇帝继位年龄小，寿命不长，多外藩入继大统
- 外戚势力的发展
- 东汉外戚、宦官的交替专权
- 豪强士族（世家大族）阶层形成于西汉后期，东汉以后发展、巩固。
- 独尊儒术之后，读书成为利禄之阶
- 余英时《士与中国文化》：一方面是强宗大姓的士族化，另一方面是士人在政治上得势后，再转而扩张家族的财势。这二方面在多数情形下当是互为因果的社会循环。
- 累世经学：学术往往局限于少数私家，遂出现
- 累世公卿：弘农杨氏（《尚书》），汝南袁氏（《易》）
- 累世经学与累世公卿，便造成士族传袭的势力，加之察举中权门请托和故旧报恩的结合，久而久之，逐步形成了社会中的门第。
- 豪强士族的庄园经济：“有求必给”、”闭门成市”，自给自足成为东汉庄园经济的一个很大特点
- 大部分社会财富不是作为赋税流入国库，而是被东汉豪强所攫取，地方豪强与中央政府的矛盾逐渐突出

## 豪强士族与中央集权政府之矛盾

- 度田的首要任务是检核人丁，人口争夺
- 小民负县官不过身死，负兵家灭门殄世
- 三国较之东汉，户数下降86.3%，口数下降86.4%
- 唐长孺：著籍户口远远低于实际户口，专制皇权的强弱一般决定于对直接控制农民的力量
- 各级地方长官有任期，而地方僚佐多世袭，因此东汉时期的地方政权在一定程度上是由当地大姓、冠族控制的

## 东汉瓦解与三国鼎立

- 黄巾起义，天下大乱
- 刺史、太守主兵的制度，由沿边州郡推广至腹地，诱发割据
- 曹操：“挟天子而令诸侯” 任用“不仁不孝而有治国用兵之术”
- 诸葛亮北伐：以攻为守，谋图自存
- 田余庆：孙氏霸业稽延，症结盖在于调整与江东大族关系的需要……其内核则是求得孙吴政权的江东地域化
- 屯田制度是豪强大土地经营方式的模拟，屯田即是国家的私田，屯田客即是国家的私客- 曹魏的士家制度和孙吴的世袭领兵制都是世袭兵。这种世代为兵的士家另有士籍，不入州郡户版。曹魏的士家制和孙吴的世袭领兵制正是大姓豪门家兵的模拟
- 《中国史纲要》：屯田制和士家制，就是国家在特定条件下用豪强征敛的方式剥削国家佃客、用私人部曲方式组织国家军队的制度

## 秦汉以来的民族问题

- 长城外的统一政权：匈奴
- 白马之围与和亲
- 汉武帝北击匈奴的三次战役
- 从公元前127年到公元后91年：匈奴国的衰微和分裂时期
- 东汉建武二十四年，匈奴在连年旱蝗后，发生内讧，匈奴分裂为南北两部。南匈奴附汉，入居塞内，进而内迁
- 东汉对南匈奴的政策：稳定和监视
- 东汉对北匈奴的政策：隔离和封锁
- 北匈奴灭亡，残部加入鲜卑

## 西晋的短暂统一

- 统治集团严重奢侈腐化
- 玄学盛行，重物质享受
- 宗王权重，以宗室巩卫皇权，王国力量不强，宗王担任都督，手握重兵且控制战略要地
- 八王之乱
- 民族内迁引发的民族矛盾：五胡乱华
- 永嘉之乱：匈奴贵族起兵灭西晋
- 中原的汉人纷纷外迁

## 南北政治大势

- 东晋vs前秦vs高车
- 宋vs北魏vs柔然
- 陈vs周vs齐vs突厥
- 南强北弱到南弱北强
- 东晋门阀政治到南朝皇权政治
- 皇帝从高级士族到低级士族到寒人
- 朝廷从士族当权到寒人兴起
- 南北统一的三次战争：淝水之战 瓜步之战 平陈之战
- 北方最终统一，南朝灭亡

## 门阀政治与门阀制度

- 仕宦之家门前记述功状的柱子，左边的叫“阀”，右边的称“阅”；先秦以来，阅仅指个人仕途中的功劳；东汉出仕者的阀阅便又成为家族荣誉、声望的标志；魏晋南北朝时期，门阀相当于门第
- 田余庆：门阀政治，质言之，是指士族与皇权的共治，是一种在特定条件下出现的皇权政治的变态，严格意义的门阀政治只存在于江左的东晋时期。
- 东晋门阀政治的代表家族：琅邪王氏 颍川庾氏 谯国桓氏 陈郡谢氏 太原王氏
- 王与马，共天下
- 谷川道雄：与财产、权势的世俗欲望相对，是士大夫的自我抑制精神实现了家族、宗族、乡党，……六朝贵族的阶级地位，正是以这种乡论为基础而形成的，而正是这种乡论才是他们得以超越王朝权力而获得自立的社会地位的根基。……六朝贵族就是这样成为道德共同体的领袖的。
- 唐长孺：门阀制度的特点是按照门户等级区别士庶在经济、政治、文化上所处的不同地位。
- 门阀制度形成于曹魏，西晋，以官品决定人品和门第高下；鼎盛于东晋，南北朝，门品决定官品，户籍上的士庶界限，一般说不再是以九品官品之有无，而是由血缘关系区别的门阀高低来划分，社会风气上，士庶界限森严；衰落于南北朝后期，士族在官吏选拔与任用上所享有的特权逐渐削弱，寒人或庶人在官员中比重增加。
- 南朝衰糜之气，空谈论玄

## 胡化汉化与北朝主流论

- 北魏汉化：定姓族、改汉姓，禁止鲜卑服饰、鲜卑语言，鲜卑贵族死后不能归葬
- 六镇胡化：六镇之乱（523-525）直接导致了北魏的瓦解，东魏北齐重新使用鲜卑语，西魏宇文泰不但恢复了胡族诸将的胡姓，还向汉人广赐胡姓，不论是复汉姓还是赐胡姓，目的都是加强社会的整合，结果都是有助于胡汉民族的融合
- 陈寅恪：边塞六镇之鲜卑及胡化之汉族，则仍保留其本来之胡化，而不为洛都汉化之所浸染。故中央政权所在之洛阳其汉化愈深，则边塞六镇胡化民族对于汉化之反动亦愈甚，卒酿成六镇之叛乱。
- 北周王光、叱罗招男夫妇墓志：迁洛集团与六镇集团之间的鸿沟通过联姻而减小甚至弥合，二者在新的政治形势下结合在了一起，构成了新的统治集团。
- 汉化是北魏孝文帝改汉姓的目的，但胡化并不是西魏复、赐胡姓的目的。
- 唐长孺：无论从服饰和风度上，都显示了汉人生活中所受鲜卑文化的影响。河北境内骑射之风的流行，反映了晋末以来北方民族对汉族的巨大影响。
- 田余庆：从宏观考察东晋南朝近三百年总的政治体制，主流是皇权政治而非门阀政治。……从宏观来看东晋南朝和十六国北朝全部历史运动的总体，其主流毕竟在北而不在南。
- 阎步克：在汉唐盛世之间，魏晋南北朝时代是个帝国衰微的低谷，而北朝构成了走出低谷、通向隋唐王朝的历史出口。
- 费孝通：汉族的壮大并不是单纯人口的自然增长，更重要的是靠吸收进入农业地区的非汉人，所以说是像滚雪球那样越滚越大。
- 陈寅恪：李唐一族之所以崛兴，盖取塞外野蛮精悍之血，注入中原文化颓废之躯，旧染既除，新机重启，扩大恢张，遂能别创空前之世局。

## 回归大一统

- 田余庆：中国历史聚少离多，聚则一统，经济发展集中于首都，发展不平衡；离则自立自存，发展地方工程，为下次统一奠基。周期发展
- 隋唐统一实际是关陇集团的联姻与统治
- 州郡县三级统治造成人浮于事，隋代改回两级
- 长官与佐官不同时迁调，官员中央任命课考，加强中央集权
- 修建东都洛阳，开凿大运河
- 隋炀帝无道，但运河开万世之利
- 大运河贯通南北，东西之争转为南北之争
- 陈寅恪：自武曌主持中央政权之后，逐渐破坏传统之“关中本位政策”…故武周之代李唐，不仅为政治之变迁，实亦社会之革命。
- 开天盛世：官民俱富，战事俱废
- 军事有折冲府，军民一体，“举关中之众以临四方”，天宝后设立节度使，由内重外轻到内轻外重，重用蕃将、委以重权
- 安史之乱后，道与方镇合一，各地藩镇割据，中央控制区南移
- 德宗起加强中央禁军神策军建设，宦官主管与地方对立
- 唐后期宦官专权，直接威胁皇权，掌握皇帝的废立，“汉不握兵，唐握兵故也”
- 朱全忠引兵诛宦官，称帝灭唐

## 承上启下的隋唐制度

- 陈寅恪：综括言之，唐代之史可分前后二期，前期结束南北朝相承之旧局面，后期开启赵宋以降之新局面，关于政治社会经济如此，关于文化学术者亦莫不如此。
- 尚书省：有尚书符，属官由皇帝任命，三公为虚职
- 中书省：草诏之责
- 门下省：发布诏书，从伺候皇帝到掌符玺
- 上午议政决策，下午六部执行
- 监察机构：御史台
- 三省特点：集体宰相制 分层决策的机制 决策与行政分离 门下省处于枢纽地位
- 中书门下取代政事堂，掌握了从决策到执行的全部权力，三省制瓦解
- 使职差遣的流行：为使则重，为官则轻
- 科举：科举制是隋唐时期兴起的一种通过考试选拔官员的制度。分常科和制科两种，常科每年举行，制科则根据需要临时举行。 同时，门荫入仕和杂色入流也是唐代重要的入仕途径
- 常科里秀才太少取消，明经，进士居多，明法明书明算后来取消，进士科在唐后期成为选拔高级官员的主要来源
- 进士科录取标准的变化：文章（词藻）—诗赋—文章（内容）
- 前期均田制与租庸调制到两税法(户无主客，以见（现）居为簿；人无丁中，以贫富为差) 从税丁到税产 

> 王梵志诗 · 贫穷田舍汉
> 
> 贫穷田舍汉，菴子极孤栖。两共前生种，今世作夫妻。
> 妇即客舂捣，夫即客扶犁。黄昏到家里，无米复无柴。
> 男女空饿肚，状似一食斋。里正催庸调，村头共相催。
> 幞头巾子露，衫破肚皮开。体上无禈绔，足下复无鞋。
> 丑妇来恶骂，啾唧搦头灰。里正被脚蹴，村头被拳搓。
> 驱将见明府，打脊趁回来。租调无处出，还需里正倍。
> 门前见债主，入户见贫妻。舍漏儿啼哭，重重逢苦灾。
> 如此硬穷汉，村村一两枚。 

- 工商税的骤兴：盐茶酒专卖
- 唐前期的法律体系是由“律、令、格、式”四种形式构成。律以正刑定罪，令以设范立制，格以禁违正邪，式以轨物程事，格、式分别是对律、令的补充
- 唐律以礼为本，礼法并用，八议十恶，有等级区分。法家法律面前人人平等，儒家贵贱长幼贫富不同
- 唐后期之立法形式开宋“敕令格式”之先声，皇帝说了算

## 唐代经济

- 耕地面积的扩大和新居民区的出现
- 对比汉唐，唐代对南方进行了开发
- 社会财富积累扩大

> 杜甫《忆昔》
> 忆昔开元全盛日，小邑犹藏万家室。
> 稻米流脂粟米白，公私仓廪俱丰实。

- 农业生产工具的改进和推广(曲辕犁或江东犁)
- 缪启愉：所谓二牛抬杠，是一根长长的辕从犁梢一直延伸到牛的肩部，顶端安设一根横木杠架在两头牛的肩胛上，犁地很不方便。现在改为向下弯曲的辕，配合犁槃、曲轭，淘汰了横杠直轭，缩短了犁辕长度，减轻了架压的重量，并且可以自由转动，操作起来自由灵活，又可以役使一头牛，大大提高了耕作效率。这是犁耕史上的一次重大革命。
- 配套工具基本完备，水田耕作农具已初步形成整套体系。(南方水田)
- 江南出现稻麦复种制，北方普遍实行两年三熟的轮作复种制

## 唐文化输出

- 堀敏一：古代东亚国家之所以向中国朝贡，以各种不同的形式和中国发生关系，是因为各民族的国家形成比中国迟，所以有必要向中国学习其国家机构的建制及其运作。在这个时代，东亚各国与中国的交往，是以此为中心展开，并因此获得各种文化的。中国的国家机构建制及其运作，规定于律令之中。因此，对于各国而言，重要的是学习此律令，引入律令所规定的各项制度。 
- 日本：遣唐使制度 吉备真备 空海 鉴真 学习唐制度与文化
- 大化改新，奈良时学习达到顶峰，未引进宦官制度，有选择性
- 新罗：唐介入半岛事务，完成统一，学习唐制
- 向东以和平，学习的态度输出文化，同为农耕经济，制度类似
- 向西以战争输出文化，经济基础不同，贞观年间打通丝绸之路
- 唐、吐蕃对西域和陇右的争夺：小勃律与石堡城
- 陈寅恪：唐关中乃王畿，故安西四镇为防护国家重心之要地，而小勃律所以成唐之西门也。玄宗之世，华夏、吐蕃、大食三大民族皆称盛强，中国欲保其腹心之关陇，不能不固守四镇。欲固守四镇，又不能不扼据小勃律，以制吐蕃，而断绝其与大食通援之道
- 天宝年间，唐在西域势力达到顶峰
- 怛（dá）逻斯（今哈萨克斯坦江布尔城附近）之战造成造纸术的西传

## 唐文化输入

- 张广达、王小甫：唐代是中国文化史上少有的既善于继承，又能够兼收并蓄的时代。尤其是在宗教、艺术、器用乃至习俗等方面，通过西域传来的印度、中亚、西亚文明以及通过南海传来的南亚文明，对隋唐文化的影响既深且远。其实，唐代文化本身就是一种中外、胡汉混合的文化，正是多种文化的交流会聚，才形成了绚丽多彩的唐代文明。
- 玄奘取经与佛教文化多宗派的兴盛：统一性、国际性、自主（独立）性、系统性
- 三夷教：祆教、景教和摩尼教
- 唐代的雅乐和燕乐，多以外来地命名
- 唐代的软舞和健舞
- 妇女的胡妆，外出不用帷帽，皆著胡帽，靓妆露面
- 《资治通鉴》：唐太宗：“自古皆贵中华，贱夷、狄，朕独爱之如一，故其种落皆依朕如父母，……朕所以成今日之功也。”

## 五代十国

- 五朝、54年、十四帝、八姓
- 南方分裂，北方统一，原因在南方经济发展可维持一国统治
- 文化中心从西北到东南迁移
- 兵制和藩镇的整顿：扩大中央禁军，削弱藩镇兵
- 控制藩镇：移易镇帅 分割藩镇地盘 把藩镇降为防御州、刺史州“直属京” 毁城隍、拆城防之具
- 禁军统帅跃登帝位：陈桥兵变
- 统一策略：先易后难，先南后北
- “斧声烛影”中的兄终弟及

## 祖宗之法与防弊之制

- 以防弊之政，作立国之法，先除内患后除外忧，事为之防，曲为之制
- 加强君权：稍夺其权，制其钱谷，收其精兵
- 制度设计中的分权原则：枢密院——三衙统兵体制，“以文制武”、“崇文抑武”
- “虚”三级制： 路没有统一的行政机构和单一的行政长官；在州之上，不存在单一的行政区划；州可以不通过路，直接向中央奏事
- 官、职、差遣的分离：“官”、“职”仅是俸禄高低和荣誉的代表，实际的职责和权力由“差遣” 决定。这使得官员任用更为灵活，监督、激励手段更为丰富
- 对宗室、外戚权力的制约：“赋以重禄，别无职业” ；“优之以爵禄而不责以事权”
- 邓小南：宋代的“祖宗之法”，是时代的产物，是当时的社会文化传统与政治、制度交汇作用的结晶。作为“祖宗之法”的核心内容，所谓“防弊之政”，出发点着眼于防范弊端，主要目标在于保证政治格局与社会秩序的稳定。从其客观效果来看，在当时条件下，有利于社会的谐调发展。其具体措置以“务实”为特色，不拘一格，体现出不少合理的思路，事实上渗透着创新的精神。
- 南宋抵御外侮时尾大不掉，和解后处决下放将领
- 耕地面积的扩大，商业的繁荣，商标的出现

## 宋代士大夫政治

- 与士大夫治天下
- 科举的取士范围与规模扩大
- 考试制度严密，通过皇帝殿试来“恩出主上”，防止朋党
- 余英时：“以天下为己任”涵蕴着“士”对于国家和社会事务的处理有直接参预的资格，因此它相当于一种“公民”意识。这一意识在宋以前虽存在而不够明确，直到“以天下为己任”一语出现才完全明朗化了
- 科举科目变迁：宋中期后只剩进士
- 唐明法之衰微，宋朝明法消亡、律学消失
- 法律在业已成为士大夫的必备知识和为官的基本素质后，律学失去了其存在的意义。律学的消亡并不是“士大夫始鲜知律”的原因，而是在重经义、重儒学的大背景下，政府要求“士大夫知律”之结果。通经术、明吏事、晓法律的宋代士大夫也使 “士大夫政治”由此达到了一个新境界
- 余英时：“以天下为己任”可以视为宋代“士”的一种集体意识，并不是极少数理想特别高远的士大夫所独有。
- 刘子健：北宋的特征是外向的，而南宋却在本质上趋向于内敛。

## 辽代的二元体制

- 耶律阿保机
- 大契丹－石敬瑭献燕云十六州－辽
- 传九代，圣宗在位的50年是辽朝的鼎盛时期
- 官分南北，南循汉制，北循契丹
- 南北枢密院，北为部族，南为州县
- 辽部族、州县不完全由国家直接管辖，又有隶于斡鲁朵及头下者
- 四时捺钵：辽有五京，但皇帝不住五京，四季迁徙打猎理政

## 金之入主中原

- 完颜阿骨打
- 先统一部族，在灭辽，后灭北宋，入主中原
- 传十代，辽朝始终坚持草原本位，而金朝在海陵王时代就已确立了汉地本位
- 中央：勃极烈辅政制，也就是酋长辅政
- 地方：猛安谋克制，军民一体
- 《金史》：本朝与辽室异，辽之基业，根本在山北之临潢，......我本朝皇业，根本在山南之燕
- 金熙宗诛杀宗室，废除勃极烈会议，建立听命于皇帝的汉式政务机构三省六部，贵族专政色彩大为减弱
- 《泰和律义》实为唐律
- 金版图确定以后，有计划地把大量猛安、谋克从东北移入中原、华北以及陕西、陇右之地，名为屯田军
- 猛安谋克户入居中原既久，多习汉语，衣汉服，效仿汉族生活、享乐习惯，本民族原有之尚武精神逐渐沦丧，走向积弱
- 猛安谋克户贫困化以及相关的积弱现象，成为金朝难以根除的一大痼疾
- 南宋宁宗嘉定元年（1208）“嘉定和议”后，宋、金两国都日益衰落，无力再发动战争，和议后的状况维持了下去，坐等蒙古铁骑的来临了

## 元朝汉化的迟滞与早衰

- 大蒙古国（1206－1259）《蒙古秘史》
- 成吉思汗与大蒙古国
- 建立千户、百户制度：军民一体，打破部落氏族，形成统一民族
- 创建怯薛护卫军：由贵族子弟充当大汗身边的护卫亲军。怯薛作为大汗的近臣，参与军政事务的策划、管理，在很大程度上承担了蒙古早期国家行政中枢的职能
- 创制蒙古文字
- 颁行法律与设置司法长官《大札撒》、札鲁忽赤
- 分封子弟
- 对外战争：南征与西征
- 大蒙古国的统治中心一直处于漠北草原，实行草原本位政策。对被征服地区进行掠夺性剥削，使中原地区的社会经济长期无法恢复
- 1260年，长期经营汉地的忽必烈即位称汗，建元中统，是为元世祖。汗廷以外产生了相对独立的四大汗国，大蒙古国不复存在
- 多级行省，未形成割据是因为打破地理限制设置行省，无天险，此外种族制度导致地方难于割据
- 传十代，忽必烈虽行汉法而建元朝，但对“汉法”的推行并不彻底而且推行民族歧视和民族压迫政策
- 四等人在政治上、法律上极不平等
- 元朝包括皇帝在内的蒙古贵族接受汉族文明比较缓慢，其中大多数人则相当长的时间内对中原文明十分隔膜。
- 姚大力：主奴观念进入元代君臣关系是受蒙古旧制影响的结果，并且它已渗透到汉式的皇帝——官僚关系中间
- 张帆：就中国古代皇权的发展线索而言，两宋金元是孕育明清极端专制主义皇权的关键阶段

## 朱元璋与明初政治、制度

- 开河变钞－刘富通红巾军起义－“弥勒佛下生,明王出世”－小明王韩林儿
- 朱元璋“高筑墙，广积粮，缓称王” - 大明皇帝
- 传17代，皇帝年号统一
- 行政制度初期仿效元代，中书总政事，都督掌军旅，御史掌纠察
- 明代中央机构的组织原则是分权，目的是互相牵制，彼此制约，权力集中于皇帝一人之手
- 太祖废丞相制，并永世不立
- 君使臣以礼，臣事君以忠 - 只知尊君，而不知礼臣
- 六部分割了原来宰相的权力，成为皇帝之下中央处理政务的最高一级机构。在政务运行中，六部除重大事务需要奏请皇帝批准外，日常事务可以自行处理
- 四品与内五品，皇帝任命；其余地方任命后奏请
- 都察院监察御史与六科给事中为言官，多为进士，官场活跃
- 军事制度从大都督府到五军都督府，￼军政、军旅分开。兵部(文臣)掌军政，都督府(武将)统领军旅
- 卫、所制度，世袭军职，寓兵于农，兵农合一
- 卫所制－镇戍制，对兵事频繁地区派总兵官镇守，在沿边各战略要地建置军镇，屯驻重兵，设总兵统领，形成若干军事重镇。逐渐推广到内地和京畿附近。以至凡天下要害的地方，皆设官统兵镇戍
- 作为中央差遣的巡抚和总督作为文臣来制衡总兵武将
- 《明太祖实录》：我朝罢丞相，设五府、六部、都察院、通政司、大理寺等衙门，分理天下庶务，彼此颉抗，不敢相压，事皆朝廷总之，所以稳当
- 《大明律》：“轻其轻罪，重其重罪”
- 《大诰》是明太祖亲自撰写、刊布的刑事法规，律外用刑，重典治吏，乱世用重典

## 内阁制度与宦官专权

- 内阁制度，开始品位比较低（五品以下），受诸多限制，备顾问而已
- 仁宗、宣宗以后，担任阁臣者，地位渐高。内阁票拟逐渐成为制度，英宗正统以后“始专命内阁条旨”
- 票拟：一切内外章奏送到内阁，由阁臣先看，并提出处理意见，写在纸条上，与章奏一道呈给皇帝。票拟成为内阁最重要的职掌
- 批红：皇帝看过章奏及阁臣的意见后，亲用红笔写于章奏，叫批红。
- 严嵩，张居正为内阁顶峰
- 与汉、唐相比，明代宦官数量庞大，机构发达，权力广泛。 明朝宦官机构非常庞大，重要的有十二监、四 司、八局，合称“二十四衙门”
- 明朝废了宰相，形成了部分的权力真空，这为明代宦官专权提供了空间，使得宦官得以以皇帝家奴的身份窃取了部分皇权
- 皇帝不理政事的时候，容易出现宦官专权的局面
- 明代宦官掌握东、西厂和锦衣卫，是明朝特务政治的代表，是其得以专权一因
- 在皇权制度越发成熟的明代，宦官专权并未对皇权构成威胁

## 经济发展与“资本主义萌芽”问题

- 农业：耕地扩大(超过8亿亩)，新品种引进，经营性地主的出现
- 手工业：规模扩大，天下四大镇(广东佛山镇、江西景德镇、湖北汉口镇、河南朱仙镇)
- “白银货币化”是明清商品经济发展中的重要现象
- “资本主义萌芽”问题本身有问题，资本主义的发展模式不唯一，似乎是商品经济、雇佣劳动与早期工业化
- 明代中期以后，随着经济的发展，商业化速度加剧，随之而来的则是农村人口向城市的流动，以及人们闲暇时间的增多

## 满族崛起与清朝建⽴

- 满族是女真族的后裔，明初分海西、野人与建州女真三部
- 万历年间，建州女真贵族努尔哈赤统一各部，建立后金政权
- 依据蒙文创立满文，在牛录基础上建立兵民合一的八期制度
- 皇太极建立大清，死后多尔衮摄政，明亡后吴三桂引兵入关建立清政权
- 传12代，皇帝年号统一

## 完成统一

- 谭其骧：清朝的统一，实际上是先统一的了满族的地区，即广义的满洲；再统一汉族的地区，即明王朝的故土；再统一蒙族地区和蒙族所统治的维藏等族地区。主要是满、蒙、汉三区的统一
- 统一台湾：郑成功从荷兰人手里收复台湾，康熙年间郑克塽请降，台湾收复
- 台湾设府，辖三县，隶福建，后设巡台御史加强地方官监督
- 喀尔喀蒙古部的归附：漠南蒙古早已归附，喀尔喀蒙古受漠西噶尔丹入侵，多伦诺尔会盟后归附清
- 雍正设立驻藏大臣，后乾隆年间发生叛乱，清军入藏平叛
- 乾隆十六年授予达赖喇嘛七世管理西藏权力，建立政教合一的西藏噶厦地方政权，从间接管理到直接管理
- 乾隆年间，“金瓶掣签”制度，约束达赖喇嘛权力，取消其“专主”地位，同时大大提高驻藏大臣的权力和地位，明确规定了西藏是清朝中央政府直接管辖的一个地区
- 准噶尔部为新疆地区势力最强大的蒙古力量，领袖噶尔丹受达赖支持，打算重新建立大蒙古帝国伟业，后被康熙平定
- 准噶尔部依旧扩张，攻入西藏，因内讧被乾隆出兵平定，设置伊犁将军，完成统一

## 统一的民族政策

- “修其教不易其俗，齐其政不易其宜” “分而治之”、“众建而分其势”
- 对边疆地区各族实行多种管理制度
- 对边疆民族上层人士政策：联姻、朝觐制度、围班制度、宗教政策 
- 对边疆的民族政策以立法形式确定：《理藩院则例》

## 君主集权的发展

- 尊君卑臣：从粪土臣到奴才
- 秘密立储：嫡长子容易形成两个权力中心，秘密立储选贤重于嫡长，摆脱了“嫡长”观念的束缚。排除了其他势力对皇位继承的干扰，由皇帝全权决定皇位继承人，是皇权强化的表现。同时皇子的受教育程度也非常高
- 奏折制度：清初用奏本题本经内阁票拟皇帝批准，后来引入奏折，不经内阁直达皇帝，朱批后执行。雍正以后，奏折应用的范围扩大，许多中级官员都获得了使用奏折的权力。奏折逐渐成为清朝最重要的官文书
- 《清圣祖实录》：凡一切奏折，皆朕亲批，诸王文武大臣等知有密折，莫测其所言何事，自然各加警惧修省矣。...大臣乃朕股肱耳目，所闻所见，即应上闻，若不可用露章者，应当密奏。天下大矣，朕一人闻见，岂能周知，若不令密奏，何由洞悉？
- 奏折具有密、速、详的特点。通过奏折制度，清代皇帝不仅能够多渠道地了解下情，对官僚机构和官员个人的控制也大为强化。乾隆十三年，废奏本
- 军机处：清初满族贵族参与国政，内阁权力远不及明代，且权力越来越低，康熙中期以后，参与中枢决策重任的有内阁、议政大臣会议和南书房，有军务设立军机处，军务缓和以后，军机处并未裁撤，反而职权范围渐广。军机处任职者无定员，军机大臣须每天值班，等候皇帝随时召见。当天必须处理完毕每天由下面送达的奏章，以保证军机处处理政务的效率。简、速、密
- 内务府：替代以往由阉人把持的内廷机构，“收阉宦之权，归之旗下”，立内务府掌管皇帝家务，以大臣统领，革除明代宦官二十四衙门，收宦官之权归入内务府，根绝了历史上的宦官之祸
- 督抚制度：总督专重兵制，巡抚专重吏治。督、抚例兼部（六部）院（都察院）
衔，表示他们是朝廷特派之部院大臣，具有中央官和地方官的双重属性，无衙门，没有正方形官印，使用临时遣官所用的长方形“关防“。清朝的总督、巡抚虽然位高权重，但并未构成地方权力中心、造成地方尾大不掉的局面

## 汉化与民族政策

- 清在历法，兵制等方面均沿袭明制
- 以“国语骑射”为根本国策
- 欧立德：族性标志是发展变化的，经过300年的发展，满语和骑射这些外在文化符号可能荡然无存，但是依托八旗制度，满洲人心中有分明的旗民划分，他们也明白作为旗人所享有的政治、经济、法律和社会意义，这些内在的思想最终变成一种不可磨灭的内在民族意识
- 学界对汉化与满化与其封建巅峰的关系存在争议，一方认为清被汉化，另一方认为清保持满化

## 盛世隐忧

- 清开荒无数，新修水利无数，经济增长并不慢
- 制度性腐败和集体腐败
- 文字狱和叫魂案所显示社会问题
- 孔飞力：在这个权力对普通民众来说向来稀缺的社会里，以叫魂罪名来恶意中伤成为一种突然可得的权利。对任何受到横暴的族人或贪婪的债主逼迫的人来说，这一权力为他们提供了解脱。对任何害怕迫害的人，它提供了一块盾牌。对任何想捞取好处的人，它提供了奖赏。对妒嫉者，它是一种补偿；对恶棍，它是一种权力；对虐待狂，它是一种乐趣

## END

- 感谢北京大学叶炜老师及其团队提供的MOOC
- [参考书单](http://www.douban.com/doulist/38210476/)


