--- 
title: "Notes"
author: "Miao YU"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: yufree/notes
description: "This is notes from yufree"
---

# 笔记概述 {-}

这里的笔记主要来自于公开课笔记与相关教材的读书笔记，主题相对分散，但这些知识应该为当今科研人员的基本技能。

首先科研人员要有一定的数学与统计学功底，这是最最基本的工具学科。微积分、线性代数与数值方法是必须的数学工具，统计学工具则至少明白如何进行统计推断与预测。其余的要看应用，例如数论对密码学而言就是基础。

然后就是编程技能，编程方面首先要熟悉编程的思维方法，例如递归、迭代、条件语句等，也就是知道机器怎么运转。其次就是掌握一门高级语言，例如R、python或matlab，这样你可以快速实现自己的想法。

之后就是模型思维，懂得将实际问题抽象成一个概念问题或统计问题或仿真问题，用解析或数值方法去求解模型或模拟，回答实际问题。

最后是专业知识，各个学科都有自己的概念，有些是可以抽象相通的，有些则属于特有的，要能把其他学科知识整合到自己的理论体系里。

我看好的方向：

- 人类非常态全解析：从基因组-转录组-蛋白组-代谢组-暴露组-心理学-流行病学全流程分析某种病例或不正常状态，探讨机理与解决方案
- 复杂科学：探索显示复杂现象中的数理规律与工程应用，例如仿生、动力学跟信息论等
- 决策方法：探索个体间互动过程中的行为决策方法，这是个体面向社会的融入指南，入门学科是博弈论

## 笔记目录（已完成）{-}

- 01 数据分析知识框架
- 02-10 数据科学系列课程
- 11 统计学习导论
- 12 基因组学数据分析
- 13 latex入门
- 14 生物信息学
- 15 流行病学
- 16 环境与健康
- 17 心理学
- 18 抑郁
- 19 贝叶斯统计
- 20 生存分析
- 21 数据科学与python简介
- 22 因果分析
- 23 系统思考
- 25 复杂系统

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-43118729-1', 'auto');
  ga('send', 'pageview');

</script>