---
title: "事件的互联网影响力调查"
author: "于淼"
date: "2015年4月2日"
output: slidy_presentation
---

## 问题

> A:网络事件影响力如何表述？

> B:如何基于事件影响力修正传播方式？

- A相当于描述性统计，需要掌握工具
- B相当于统计推断，需要科学框架

## 影响力

- 事件信息的出现，复制与再生

    - 出现意味着新闻播报，推送（被动）与浏览点击评论（主动）
    - 复制意味着转发
    - 再生意味着基于第一次新闻的二次创作，信息解读与注释

## 类比文献计量学

- 量化文章的影响力
- [文献计量学三定律](http://zh.wikipedia.org/wiki/%E6%9B%B8%E7%9B%AE%E8%A8%88%E9%87%8F%E5%AD%B8)

    - 布拉德福定律: 特定学科之最相关文献集中于少数的核心期刊之中
    - 洛特卡定律: 发现发表n篇论文的作者总数，是发表一篇论文作者总数的n平方分之一
    - 齐普夫定律: 发现字词的使用次数（f）与字词的使次数排名（r）之乘积，会等于一常数C

- 类比网络事件

    - 网络事件一般出现在最主流平台（核心期刊）：百度，微信，微博
    - 网络大V把持话语权，作者群长尾
    - 检索时避开高频词可有效屏蔽干扰
    
## 类比流行病学

- 三间分布

    - 时间：疾病的潜伏期，发病期，稳定期与恢复期
    - 空间：疾病的地域分布及其与地理因素间关系
    - 人群间：患者的共性与特性及与对照组的区别联系
    
- 类比网络事件

    - 时间：信息基线，高峰，衰减，基线回归
    - 空间：地域搜索量与传播渠道
    - 人群间：搜索人群的特征信息

## 影响力测算工具

- 搜索量
    
    - [百度指数](http://index.baidu.com/)
    - [谷歌趋势](http://www.google.com/trends/)
    - [微指数](http://data.weibo.com/index)

- 页面行为（需要网站页面内嵌js代码）
    
    - [谷歌分析](http://www.google.com/analytics/)
    - [百度分析](http://tongji.baidu.com/)

- 传播行为

    - [北京大学 PKUVIS 微博可视分析工具](http://vis.pku.edu.cn/weibova/weiboevents/)
    - [微信公众号后台](https://mp.weixin.qq.com/)

- 可视化

    - [文本分析](http://www.tagxedo.com/app.html)
    - [Echarts](http://echarts.baidu.com/)
    - [D3.js](http://d3js.org/)

## 案例

- [google flu](https://www.google.org/flutrends/)
- [百度迁徙](http://qianxi.baidu.com/)
- [新浪微博签到数据](http://www.thinkgis.cn/public/sina/)
- [微博用户影响力评价的H-Index指数](http://cos.name/2013/04/weibo-influence-hindex/)
- [微博名人那些事儿](http://cos.name/2013/08/something_about_weibo/)
- [粉丝地图的可视化](http://cos.name/2013/06/weibo-fans-map-visualization/)

## 个人经验

- 不论时间，空间还是人群考察，必须设定基线，否则无法对比
- 注意移动端与PC端的三间差异区别，移动端将是主流
- 区别传统媒体与社交媒体：前者的受众偏被动，转发可能小；后者受众偏主动，转发可能大，用户年龄等与前者有明显区别
- 排版，写作与新闻发布要有针对性，注意快餐式阅读风格
- 网络分析寻找关键传播人物，多群体的交集人物往往对传播价值更高
- 网络影响力很难定量考察，数据展示与演讲技巧很重要
- 千万不要学[fox](http://simplystatistics.org/2012/11/26/the-statisticians-at-fox-news-use-classic-and-novel-graphical-techniques-to-lead-with-data/)，网上大把人喜欢找茬
- 数据上垃圾进垃圾出，关键词的选择要有可检验的假设
- 想法与实践并重，工具均为免费获取，有想法最好马上进行探索
- 案例分析：[《穹顶之下》影响力测算](http://yufree.cn/blogcn/2015/03/07/chai-influence.html)

## 谢谢

- 工具使用参考工具官方主页的帮助文档
- 有疑问欢迎[联系](mailto:yufreecas@gmail.com)[我](http://yufree.cn)
