中医药
========================================================

# 阴阳论

生理最佳状态：阴平阳秘

- 真阴要有收敛收藏阴精的作用，并能滋养真阳收敛真阳（阴平）
- 真阳要有生长生发抵御外邪的作用，并不让真阴外泄而固束真阴（阳秘）

病因：阴阳失和

治病：调整阴阳

养生：调和阴阳

思想经典：黄帝内经

素问·金匮真言论

> 阴中有阴，阳中有阳。平旦至日中，天之阳，阳中之阳也；日中至黄昏，天之阳，阳中之阴也；合夜至鸡鸣，天之阴，阴中之阴也；鸡鸣至平旦，天之阴，阴中之阳也。
    
> 故人亦应之，夫言人之阴阳，则外为阳，内为阴。言人身之阴阳，则背为阳，腹为阴。言人身之脏腑中阴阳，则脏者为阴，腑者为阳。肝、心、脾、肺、肾，五脏皆为阴，胆、胃、大肠、小肠、膀胱、三焦，六腑皆为阳。
    
> 所以欲知阴中之阴，阳中之阳者，何也？为冬病在阴，夏病在阳，春病在阴，秋病在阳，皆视其所在，为施针石也。
    
> 故背为阳，阳中之阳，心也；背为阳，阳中之阴，肺也；腹为阴，阴中之阴，肾也，阴中之阳，肝也；腹为阴，阴中之至阴，脾也。
    
> 此皆阴阳表里，内外雌雄，相输应也。故以应天之阴阳也。

素问·阴阳应象大论

> 故积阳为天，积阴为地。阴静阳燥，阳生阴长，阳杀阴藏，阳化气，阴成形。
    
> 寒极生热，热极生寒，寒气生浊，热气生清。清气在下，则生飧泄；浊气在上，则生(月真)胀。此阴阳反作，病之逆从也。
    
> 故清阳为天，浊阴为地；地气上为云，天气下为雨；雨出地气，云出天气。

> 故清阳出上窍，浊阴出下窍；清阳发腠理，浊阴走五脏；清阳实四肢，浊阴归六腑。

> 阴胜则阳病，阳胜则阴病。阳胜则热，阴胜则寒。重寒则热，重热则寒。

> 寒伤形，热伤气。气伤痛，形伤肿。故先痛而后肿者，气伤形也，先肿而后痛者，形伤气也。

# 五行论

自然界的季节、方位、气候、生命规律、色彩、味道、音色与人体功能性、组成单位、情志活动、主要脉象、体液等通过五行属性相关联

核心顺序：木火土金水，临相生，间相克

相乘:五行相克太过

相侮:五行反克为害

- 以五行的特性来分析研究脏腑、经络等组织器官的五行属性
- 以五行的生克制化来分析研究各脏腑、经络之间和各生理功能之间的相互关系
- 以五行相生和相克 ( 乘侮 ) 关系的异常来阐释病理情况下的相互影响

## 传变

相生关系的传变就是病变顺着或逆着木、火、土、金、水 ( 肝、心、脾、肺、肾 ) 次序的传变。按相生关系的传变可归纳成两种类型:母病及子和子病犯母。

母病及子,是指疾病顺着相生次序的传变,由母脏发展到子脏。子病犯母,有时又称“子盗母气”,指的是疾病逆着相生关系的传变,由子脏波及到母脏。

相克关系的传变就是前面所介绍的“相乘”和“相侮”,指病变沿着或逆着脏腑相克次序的传变。相乘即相克太过为病。相侮,就是反克为病,故又称“反侮”,指的是逆着相克次序的制约为病。相乘和相侮,都是相克的异常,都属于病理状态。

## 治疗

- 通过相生相克原理控制疾病的传变
- 确定治疗原则和方法

五行学说是中医药解决复杂健康问题的系统手段,证明了系统方法的有效性,给未来医药健康问题的解决提供了思维模式。
# 脏腑理论

中医从功能而非解剖上定义脏腑。

- 脏，充满精气
- 腑，中空，转化水谷
- 藏象 脏腑生理功能，病理变化及相互关系

# 经络

在名字里出现的脏或腑,表明该经是属于该脏或腑,但该经同时还联络相表里的腑或脏。

十二经脉的流注顺序:十二经脉的流注是从手太阴肺经开始,阴阳相贯,首尾相接,逐经相传,到肝经为止,从而构成了周而复始、如环无休的流注系统。将气血周流全身,起到濡养的作用。

> 手之三阴,从胸走手;手之三阳,从手走头;足之三阳,从头走足;足之三阴,从足走腹。

经络感传与实质：疑似筋肉结缔组织

# 中药性味理论

药性实际上是指中药的性能或偏性,是中药固有的性质。

“四气”是指药物的温、热、寒、凉四种药性，“温热寒凉”表示“药物在影响人体阴阳盛衰,寒热变化方面的作用倾向”。

五味

- 辛:能散、能行。
- 散-发散解表:麻黄、桂枝、薄荷等
- 行-行气行血:香附、木香、桃仁等
- 酸:能收、能涩。
- 收-收敛止汗:浮小麦、麻黄根等
- 涩-涩肠止泻:乌梅、五倍子等 涩精止带:山茱萸、五味子、金樱子等

# 归经升降理论

- 味酸—能入肝
- 味苦—能入心
- 味辛—能入肺
- 味甘—能入脾
- 味咸—能入肾

升降沉浮是指药物作用于人体的不同趋势。升—上升;降—下降;浮—发散;沉—收敛固藏和泄利二便(向内,向下)

气机升降出入是人体生命活动的基础。当气机升降出入发生障碍,机体便处于疾病状态,产生不同病势趋向,常表现为向上(如呕吐、咳喘等症状)、向下(如泄泻、脱肛等症状)、向外(如自汗、盗汗等)、向内(如表证不解)。

# 药物毒性理论

《神农本草经》中毒性分大中小

